# Generated by Django 3.0.3 on 2020-04-14 17:08

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('name', models.CharField(max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('asset_links', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, size=100)),
            ],
        ),
    ]
