# Generated by Django 2.2.5 on 2019-10-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='default_article.jpg', upload_to='article_pics'),
        ),
    ]
