# Generated by Django 2.2.5 on 2019-10-02 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0002_auto_20191001_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='default_article.png', upload_to='article_pics'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default='default_news.png', upload_to='news_pics'),
        ),
    ]
