# Generated by Django 2.2.5 on 2019-12-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity_Static_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=16)),
                ('country', models.CharField(choices=[('G', 'Global'), ('USA', 'United States'), ('UK', 'United Kingdom')], max_length=3)),
                ('base_symbol', models.CharField(max_length=6)),
                ('contract_size', models.CharField(max_length=30)),
                ('settlement_type', models.CharField(default='Physical', max_length=30)),
                ('tick_size', models.CharField(max_length=30)),
                ('tick_value', models.CharField(max_length=30)),
                ('months', models.CharField(max_length=30)),
            ],
        ),
    ]
