# Generated by Django 2.2.5 on 2019-12-02 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0004_crpytocurrencystaticinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CrpytoCurrencyStaticInfo',
            new_name='CryptoCurrencyStaticInfo',
        ),
    ]
