# Generated by Django 2.2.5 on 2019-12-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0005_auto_20191202_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='USStockStaticInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=12)),
                ('long_name', models.CharField(max_length=50)),
                ('country', models.CharField(choices=[('G', 'Global'), ('USA', 'United States of America'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('HK', 'Honk Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], default='USA', max_length=3)),
                ('market', models.CharField(choices=[('NYSE', 'New York Stock Exchange'), ('NASDAQ', 'NASDAQ Stock Market')], max_length=10)),
                ('isin', models.CharField(max_length=12)),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name': "US's Stocks Static Info",
                'verbose_name_plural': "US's Stocks Static Info",
            },
        ),
        migrations.AlterModelOptions(
            name='commoditystaticinfo',
            options={'verbose_name': "Commodities' Static Info", 'verbose_name_plural': "Commodities' Static Info"},
        ),
        migrations.AlterModelOptions(
            name='cryptocurrencystaticinfo',
            options={'verbose_name': "Cryptocurrencies' Static Info", 'verbose_name_plural': "Cryptocurrencies' Static Info"},
        ),
        migrations.AlterModelOptions(
            name='currencystaticinfo',
            options={'verbose_name': "Currencies' Static Info", 'verbose_name_plural': "Currencies' Static Info"},
        ),
        migrations.AlterField(
            model_name='commoditystaticinfo',
            name='country',
            field=models.CharField(choices=[('G', 'Global'), ('USA', 'United States of America'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('HK', 'Honk Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], max_length=3),
        ),
        migrations.AlterField(
            model_name='cryptocurrencystaticinfo',
            name='long_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='currencystaticinfo',
            name='long_name',
            field=models.CharField(max_length=50),
        ),
    ]
