# Generated by Django 2.2.5 on 2019-12-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0006_auto_20191203_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usstockstaticinfo',
            name='market',
            field=models.CharField(choices=[('NYSE', 'New York Stock Exchange'), ('NASDAQ', 'NASDAQ Stock Market'), ('OTC Markets', 'Over-The-Counter Markets')], max_length=11),
        ),
    ]
