# Generated by Django 2.2.5 on 2019-12-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0007_auto_20191206_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usstockstaticinfo',
            name='long_name',
            field=models.CharField(max_length=60),
        ),
    ]
