# Generated by Django 2.2.5 on 2019-12-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0009_auto_20191206_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='japanstockstaticinfo',
            name='market',
            field=models.CharField(choices=[('Tokyo', 'Tokyo Stock Exchange - (TYO)'), ('Osaka', 'Osaka Securities Exchange'), ('Nagoya', 'Nagoya Stock Exchange - (NSE)'), ('Fukuoka', 'Fukuoka Stock Exchange - (FSE)'), ('Sapporo', 'Sapporo Securities Exchange'), ('JASDAQ', 'JASDAQ Securities Exchange')], max_length=20),
        ),
    ]
