# Generated by Django 2.2.5 on 2019-12-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0010_auto_20191206_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='UKStockStaticInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=12)),
                ('long_name', models.CharField(max_length=60)),
                ('country', models.CharField(choices=[('G', 'Global'), ('USA', 'United States of America'), ('UK', 'United Kingdom'), ('JPN', 'Japan'), ('HK', 'Honk Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], default='UK', max_length=3)),
                ('market', models.CharField(choices=[('London', 'London Stock Exchange')], max_length=20)),
                ('isin', models.CharField(max_length=12)),
                ('link', models.URLField()),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('JPY', 'Japanese Yen'), ('GBP', 'Pound Sterling')], default='GBP', max_length=3)),
            ],
            options={
                'verbose_name': "UK's Stocks Static Info",
                'verbose_name_plural': "UK's Stocks Static Info",
            },
        ),
        migrations.AlterField(
            model_name='japanstockstaticinfo',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('JPY', 'Japanese Yen'), ('GBP', 'Pound Sterling')], default='JPY', max_length=3),
        ),
        migrations.AlterField(
            model_name='usstockstaticinfo',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('JPY', 'Japanese Yen'), ('GBP', 'Pound Sterling')], default='USD', max_length=3),
        ),
    ]
