# Generated by Django 2.2.5 on 2019-12-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0013_auto_20191207_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChinaStockStaticInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=12)),
                ('long_name', models.CharField(max_length=60)),
                ('country', models.CharField(choices=[('G', 'Global'), ('USA', 'United States of America'), ('UK', 'United Kingdom'), ('JPN', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], default='CH', max_length=3)),
                ('market', models.CharField(choices=[('Shanghai', 'Shanghai Stock Exchange - (SSE)'), ('Shenzhen', 'Shenzhen Stock Exchange')], max_length=20)),
                ('isin', models.CharField(max_length=12)),
                ('link', models.URLField()),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('JPY', 'Japanese Yen'), ('GBP', 'Pound Sterling'), ('HKD', 'Hong Kong Dollar'), ('CNY', 'Chinese Yuan')], default='CNY', max_length=3)),
            ],
            options={
                'verbose_name': 'China Stocks Static Info',
                'verbose_name_plural': 'China Stocks Static Info',
            },
        ),
        migrations.AlterField(
            model_name='hkstockstaticinfo',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('JPY', 'Japanese Yen'), ('GBP', 'Pound Sterling'), ('HKD', 'Hong Kong Dollar'), ('CNY', 'Chinese Yuan')], default='HKD', max_length=3),
        ),
        migrations.AlterField(
            model_name='japanstockstaticinfo',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('JPY', 'Japanese Yen'), ('GBP', 'Pound Sterling'), ('HKD', 'Hong Kong Dollar'), ('CNY', 'Chinese Yuan')], default='JPY', max_length=3),
        ),
        migrations.AlterField(
            model_name='ukstockstaticinfo',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('JPY', 'Japanese Yen'), ('GBP', 'Pound Sterling'), ('HKD', 'Hong Kong Dollar'), ('CNY', 'Chinese Yuan')], default='GBP', max_length=3),
        ),
        migrations.AlterField(
            model_name='usstockstaticinfo',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('JPY', 'Japanese Yen'), ('GBP', 'Pound Sterling'), ('HKD', 'Hong Kong Dollar'), ('CNY', 'Chinese Yuan')], default='USD', max_length=3),
        ),
    ]
