# Generated by Django 2.2.7 on 2019-12-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0014_auto_20191207_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chinastockstaticinfo',
            name='long_name',
            field=models.CharField(max_length=70),
        ),
    ]
