# Generated by Django 2.2.7 on 2019-12-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0015_auto_20191207_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chinastockstaticinfo',
            name='long_name',
            field=models.CharField(max_length=75),
        ),
    ]
