# Generated by Django 2.2.7 on 2019-12-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0016_auto_20191207_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hkstockstaticinfo',
            name='isin',
            field=models.CharField(max_length=13),
        ),
    ]
