# Generated by Django 2.2.7 on 2019-12-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0017_auto_20191208_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hkstockstaticinfo',
            name='isin',
            field=models.CharField(max_length=12),
        ),
    ]
