# Generated by Django 2.2.7 on 2019-12-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0021_auto_20191208_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanadaStockStaticInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=6)),
                ('long_name', models.CharField(max_length=75)),
                ('country', models.CharField(choices=[('G', 'Global'), ('USA', 'United States of America'), ('UK', 'United Kingdom'), ('JPN', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], default='CA', max_length=3)),
                ('market', models.CharField(choices=[('NEO', 'Aequitas Neo Exchange (NEO)'), ('Toronto', 'Toronto Stock Exchange (TSX)'), ('CSE', 'Canadian Securities Exchange (CSE)'), ('NASDAQ', 'NASDAQ Canada')], max_length=20)),
                ('isin', models.CharField(max_length=12)),
                ('link', models.URLField()),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('JPY', 'Japanese Yen'), ('GBP', 'Pound Sterling'), ('HKD', 'Hong Kong Dollar'), ('CNY', 'Chinese Yuan'), ('CAD', 'Canadian Dollar')], default='CAD', max_length=3)),
            ],
            options={
                'verbose_name': 'Canada Stocks Static Info',
                'verbose_name_plural': 'Canada Stocks Static Info',
            },
        ),
        migrations.AlterField(
            model_name='chinastockstaticinfo',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('JPY', 'Japanese Yen'), ('GBP', 'Pound Sterling'), ('HKD', 'Hong Kong Dollar'), ('CNY', 'Chinese Yuan'), ('CAD', 'Canadian Dollar')], default='CNY', max_length=3),
        ),
        migrations.AlterField(
            model_name='hkstockstaticinfo',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('JPY', 'Japanese Yen'), ('GBP', 'Pound Sterling'), ('HKD', 'Hong Kong Dollar'), ('CNY', 'Chinese Yuan'), ('CAD', 'Canadian Dollar')], default='HKD', max_length=3),
        ),
        migrations.AlterField(
            model_name='japanstockstaticinfo',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('JPY', 'Japanese Yen'), ('GBP', 'Pound Sterling'), ('HKD', 'Hong Kong Dollar'), ('CNY', 'Chinese Yuan'), ('CAD', 'Canadian Dollar')], default='JPY', max_length=3),
        ),
        migrations.AlterField(
            model_name='japanstockstaticinfo',
            name='market',
            field=models.CharField(choices=[('Tokyo', 'Tokyo Stock Exchange (TYO)'), ('Osaka', 'Osaka Securities Exchange'), ('Nagoya', 'Nagoya Stock Exchange (NSE)'), ('Fukuoka', 'Fukuoka Stock Exchange (FSE)'), ('Sapporo', 'Sapporo Securities Exchange'), ('JASDAQ', 'JASDAQ Securities Exchange')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ukstockstaticinfo',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('JPY', 'Japanese Yen'), ('GBP', 'Pound Sterling'), ('HKD', 'Hong Kong Dollar'), ('CNY', 'Chinese Yuan'), ('CAD', 'Canadian Dollar')], default='GBP', max_length=3),
        ),
        migrations.AlterField(
            model_name='usstockstaticinfo',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('JPY', 'Japanese Yen'), ('GBP', 'Pound Sterling'), ('HKD', 'Hong Kong Dollar'), ('CNY', 'Chinese Yuan'), ('CAD', 'Canadian Dollar')], default='USD', max_length=3),
        ),
    ]
