# Generated by Django 2.2.7 on 2019-12-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0022_auto_20191210_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canadastockstaticinfo',
            name='long_name',
            field=models.CharField(max_length=51),
        ),
    ]
