# Generated by Django 2.2.7 on 2019-12-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0025_auto_20191210_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='germanystockstaticinfo',
            name='short_name',
            field=models.CharField(max_length=8),
        ),
    ]
