# Generated by Django 2.2.7 on 2019-12-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0027_auto_20191211_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='australiastockstaticinfo',
            name='long_name',
            field=models.CharField(max_length=49),
        ),
    ]
