# Generated by Django 2.2.7 on 2019-12-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0033_auto_20191213_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='japanindexstaticinfo',
            name='long_name',
            field=models.CharField(max_length=49),
        ),
    ]
