# Generated by Django 2.2.7 on 2019-12-13 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0034_auto_20191213_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='japanindexstaticinfo',
            name='isin',
        ),
    ]
