# Generated by Django 2.2.7 on 2019-12-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0035_remove_japanindexstaticinfo_isin'),
    ]

    operations = [
        migrations.CreateModel(
            name='UKIndexStaticInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=12)),
                ('long_name', models.CharField(max_length=60)),
                ('country', models.CharField(choices=[('G', 'Global'), ('USA', 'United States of America'), ('UK', 'United Kingdom'), ('JPN', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], default='UK', max_length=3)),
                ('market', models.CharField(choices=[('London', 'London Stock Exchange')], default='London', max_length=20)),
                ('link', models.URLField()),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('JPY', 'Japanese Yen'), ('GBP', 'Pound Sterling'), ('HKD', 'Hong Kong Dollar'), ('CNY', 'Chinese Yuan'), ('CAD', 'Canadian Dollar'), ('EUR', 'Euro'), ('AUD', 'Australian Dollar')], default='GBP', max_length=3)),
            ],
            options={
                'verbose_name': 'United Kingdom Indices Static Info',
                'verbose_name_plural': 'United Kingdom Indices Static Info',
            },
        ),
    ]
