# Generated by Django 2.2.7 on 2019-12-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0038_auto_20191213_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hkindexstaticinfo',
            name='short_name',
            field=models.CharField(max_length=8),
        ),
    ]
