# Generated by Django 2.2.7 on 2019-12-13 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0040_auto_20191213_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChinaIndexStaticInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=6)),
                ('long_name', models.CharField(max_length=75)),
                ('country', models.CharField(choices=[('G', 'Global'), ('USA', 'United States of America'), ('UK', 'United Kingdom'), ('JPN', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], default='CH', max_length=3)),
                ('market', models.CharField(choices=[('Shanghai', 'Shanghai Stock Exchange'), ('Shenzhen', 'Shenzhen Stock Exchange')], max_length=8)),
                ('link', models.URLField()),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('JPY', 'Japanese Yen'), ('GBP', 'Pound Sterling'), ('HKD', 'Hong Kong Dollar'), ('CNY', 'Chinese Yuan'), ('CAD', 'Canadian Dollar'), ('EUR', 'Euro'), ('AUD', 'Australian Dollar')], default='CNY', max_length=3)),
            ],
            options={
                'verbose_name': 'China Indices Static Info',
                'verbose_name_plural': 'China Indices Static Info',
            },
        ),
    ]
