# Generated by Django 2.2.7 on 2019-12-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0041_chinaindexstaticinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chinaindexstaticinfo',
            name='long_name',
            field=models.CharField(max_length=56),
        ),
    ]
