# Generated by Django 2.2.7 on 2019-12-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0042_auto_20191213_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chinaindexstaticinfo',
            name='short_name',
            field=models.CharField(max_length=12),
        ),
    ]
