# Generated by Django 2.2.7 on 2019-12-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0044_canadaindexstaticinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canadaindexstaticinfo',
            name='long_name',
            field=models.CharField(max_length=44),
        ),
    ]
