# Generated by Django 2.2.7 on 2019-12-13 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0045_auto_20191213_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canadaindexstaticinfo',
            name='short_name',
            field=models.CharField(max_length=12),
        ),
    ]
