# Generated by Django 2.2.7 on 2019-12-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0046_auto_20191213_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canadastockstaticinfo',
            name='market',
            field=models.CharField(choices=[('NEO', 'Aequitas Neo Exchange (NEO)'), ('Toronto', 'Toronto Stock Exchange (TSX)'), ('CSE', 'Canadian Securities Exchange (CSE)'), ('NASDAQ', 'NASDAQ Canada')], max_length=7),
        ),
    ]
