# Generated by Django 2.2.7 on 2019-12-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0048_auto_20191214_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='germanyindexstaticinfo',
            name='long_name',
            field=models.CharField(max_length=46),
        ),
    ]
