# Generated by Django 2.2.7 on 2019-12-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0049_auto_20191214_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='AustraliaIndexStaticInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=8)),
                ('long_name', models.CharField(max_length=49)),
                ('country', models.CharField(choices=[('G', 'Global'), ('USA', 'United States of America'), ('UK', 'United Kingdom'), ('JPN', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], default='AU', max_length=3)),
                ('market', models.CharField(choices=[('ASX', 'Australian Securities Exchange')], default='ASX', max_length=3)),
                ('link', models.URLField()),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('JPY', 'Japanese Yen'), ('GBP', 'Pound Sterling'), ('HKD', 'Hong Kong Dollar'), ('CNY', 'Chinese Yuan'), ('CAD', 'Canadian Dollar'), ('EUR', 'Euro'), ('AUD', 'Australian Dollar')], default='AUD', max_length=3)),
            ],
            options={
                'verbose_name': 'Australia Indices Static Info',
                'verbose_name_plural': 'Australia Indices Static Info',
            },
        ),
    ]
