# Generated by Django 2.2.7 on 2019-12-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0050_australiaindexstaticinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='australiaindexstaticinfo',
            name='long_name',
            field=models.CharField(max_length=47),
        ),
        migrations.AlterField(
            model_name='australiaindexstaticinfo',
            name='short_name',
            field=models.CharField(max_length=12),
        ),
    ]
