# Generated by Django 2.2.7 on 2019-12-14 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0054_auto_20191214_1955'),
    ]

    operations = [
        migrations.DeleteModel(
            name='X',
        ),
    ]
