# Generated by Django 2.2.7 on 2019-12-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0055_auto_20191215_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='X',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
