# Generated by Django 2.2.7 on 2019-12-15 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0056_x'),
    ]

    operations = [
        migrations.DeleteModel(
            name='X',
        ),
    ]
