# Generated by Django 2.2.7 on 2019-12-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0057_delete_x'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usetfstaticinfo',
            name='issuer',
            field=models.CharField(max_length=32),
        ),
    ]
