# Generated by Django 2.2.7 on 2019-12-15 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0058_auto_20191215_1447'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AustraliaETFStaticInfo',
        ),
        migrations.DeleteModel(
            name='CanadaETFStaticInfo',
        ),
        migrations.DeleteModel(
            name='ChinaETFStaticInfo',
        ),
        migrations.DeleteModel(
            name='GermanyETFStaticInfo',
        ),
        migrations.DeleteModel(
            name='HKETFStaticInfo',
        ),
        migrations.DeleteModel(
            name='JapanETFStaticInfo',
        ),
        migrations.DeleteModel(
            name='UKETFStaticInfo',
        ),
        migrations.DeleteModel(
            name='USETFStaticInfo',
        ),
    ]
