# Generated by Django 2.2.7 on 2019-12-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0063_auto_20191215_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usetfstaticinfo',
            name='country',
            field=models.CharField(choices=[('G', 'Global'), ('US', 'United States of America'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], default='US', max_length=2),
        ),
    ]
