# Generated by Django 2.2.7 on 2019-12-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0065_auto_20191215_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='AustraliaBondStaticInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=13)),
                ('long_name', models.CharField(max_length=28)),
                ('country', models.CharField(choices=[('G', 'Global'), ('US', 'United States of America'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], default='AU', max_length=2)),
                ('market', models.CharField(choices=[('ASX', 'Australian Securities Exchange')], default='ASX', max_length=3)),
                ('link', models.URLField()),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('JPY', 'Japanese Yen'), ('GBP', 'Pound Sterling'), ('HKD', 'Hong Kong Dollar'), ('CNY', 'Chinese Yuan'), ('CAD', 'Canadian Dollar'), ('EUR', 'Euro'), ('AUD', 'Australian Dollar')], default='AUD', max_length=3)),
            ],
            options={
                'verbose_name': "Australia Bonds' Static Info",
                'verbose_name_plural': "Australia Bonds' Static Info",
            },
        ),
        migrations.CreateModel(
            name='CanadaBondStaticInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=10)),
                ('long_name', models.CharField(max_length=25)),
                ('country', models.CharField(choices=[('G', 'Global'), ('US', 'United States of America'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], default='CA', max_length=2)),
                ('market', models.CharField(choices=[('NEO', 'Aequitas Neo Exchange (NEO)'), ('Toronto', 'Toronto Stock Exchange (TSX)'), ('CSE', 'Canadian Securities Exchange (CSE)'), ('NASDAQ', 'NASDAQ Canada'), ('TSXV', 'TSX Venture Exchange (TSXV)')], max_length=7)),
                ('link', models.URLField()),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('JPY', 'Japanese Yen'), ('GBP', 'Pound Sterling'), ('HKD', 'Hong Kong Dollar'), ('CNY', 'Chinese Yuan'), ('CAD', 'Canadian Dollar'), ('EUR', 'Euro'), ('AUD', 'Australian Dollar')], default='CAD', max_length=3)),
            ],
            options={
                'verbose_name': "Canada Bonds' Static Info",
                'verbose_name_plural': "Canada Bonds' Static Info",
            },
        ),
        migrations.CreateModel(
            name='ChinaBondStaticInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=9)),
                ('long_name', models.CharField(max_length=24)),
                ('country', models.CharField(choices=[('G', 'Global'), ('US', 'United States of America'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], default='CH', max_length=2)),
                ('market', models.CharField(choices=[('Shanghai', 'Shanghai Stock Exchange'), ('Shenzhen', 'Shenzhen Stock Exchange')], max_length=20)),
                ('link', models.URLField()),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('JPY', 'Japanese Yen'), ('GBP', 'Pound Sterling'), ('HKD', 'Hong Kong Dollar'), ('CNY', 'Chinese Yuan'), ('CAD', 'Canadian Dollar'), ('EUR', 'Euro'), ('AUD', 'Australian Dollar')], default='CNY', max_length=3)),
            ],
            options={
                'verbose_name': "China Bonds' Static Info",
                'verbose_name_plural': "China Bonds' Static Info",
            },
        ),
        migrations.CreateModel(
            name='GermanyBondStaticInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=11)),
                ('long_name', models.CharField(max_length=26)),
                ('country', models.CharField(choices=[('G', 'Global'), ('US', 'United States of America'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], default='GE', max_length=2)),
                ('market', models.CharField(choices=[('Frankfurt', 'Frankfurt Stock Exchange (XFRA)'), ('Berlin', 'Berlin Stock Exchange (XBER)'), ('Xetra', 'Xetra Stock Exchange (XETR)'), ('Munich', 'Munich Stock Exchange (XMUN)'), ('Stuttgart', 'Stuttgart Stock Exchange (XSTU)'), ('Dusseldorf', 'Dusseldorf Stock Exchange(XDUS)'), ('Hamburg', 'Hamburg Stock Exchange(XHAM)'), ('Hannover', 'Hannover Stock Exchange (XHAN)')], max_length=20)),
                ('link', models.URLField()),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('JPY', 'Japanese Yen'), ('GBP', 'Pound Sterling'), ('HKD', 'Hong Kong Dollar'), ('CNY', 'Chinese Yuan'), ('CAD', 'Canadian Dollar'), ('EUR', 'Euro'), ('AUD', 'Australian Dollar')], default='EUR', max_length=3)),
            ],
            options={
                'verbose_name': "Germany Bonds' Static Info",
                'verbose_name_plural': "Germany Bonds' Static Info",
            },
        ),
        migrations.CreateModel(
            name='HKBondStaticInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=13)),
                ('long_name', models.CharField(max_length=28)),
                ('country', models.CharField(choices=[('G', 'Global'), ('US', 'United States of America'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], default='HK', max_length=2)),
                ('market', models.CharField(choices=[('HKG', 'The Stock Exchange of Hong Kong Limited')], default='HKG', max_length=3)),
                ('link', models.URLField()),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('JPY', 'Japanese Yen'), ('GBP', 'Pound Sterling'), ('HKD', 'Hong Kong Dollar'), ('CNY', 'Chinese Yuan'), ('CAD', 'Canadian Dollar'), ('EUR', 'Euro'), ('AUD', 'Australian Dollar')], default='HKD', max_length=3)),
            ],
            options={
                'verbose_name': "Hong Kong Bonds' Static Info",
                'verbose_name_plural': "Hong Kong Bonds' Static Info",
            },
        ),
        migrations.CreateModel(
            name='JapanBondStaticInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=10)),
                ('long_name', models.CharField(max_length=24)),
                ('country', models.CharField(choices=[('G', 'Global'), ('US', 'United States of America'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], default='JP', max_length=2)),
                ('market', models.CharField(choices=[('Tokyo', 'Tokyo Stock Exchange (TYO)'), ('Osaka', 'Osaka Securities Exchange'), ('Nagoya', 'Nagoya Stock Exchange (NSE)'), ('Fukuoka', 'Fukuoka Stock Exchange (FSE)'), ('Sapporo', 'Sapporo Securities Exchange'), ('JASDAQ', 'JASDAQ Securities Exchange')], max_length=7)),
                ('link', models.URLField()),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('JPY', 'Japanese Yen'), ('GBP', 'Pound Sterling'), ('HKD', 'Hong Kong Dollar'), ('CNY', 'Chinese Yuan'), ('CAD', 'Canadian Dollar'), ('EUR', 'Euro'), ('AUD', 'Australian Dollar')], default='JPY', max_length=3)),
            ],
            options={
                'verbose_name': "Japan Bonds' Static Info",
                'verbose_name_plural': "Japan Bonds' Static Info",
            },
        ),
        migrations.CreateModel(
            name='UKBondStaticInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=8)),
                ('long_name', models.CharField(max_length=33)),
                ('country', models.CharField(choices=[('G', 'Global'), ('US', 'United States of America'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], default='UK', max_length=2)),
                ('market', models.CharField(choices=[('London', 'London Stock Exchange')], default='London', max_length=20)),
                ('link', models.URLField()),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('JPY', 'Japanese Yen'), ('GBP', 'Pound Sterling'), ('HKD', 'Hong Kong Dollar'), ('CNY', 'Chinese Yuan'), ('CAD', 'Canadian Dollar'), ('EUR', 'Euro'), ('AUD', 'Australian Dollar')], default='GBP', max_length=3)),
            ],
            options={
                'verbose_name': "United Kingdom Bonds' Static Info",
                'verbose_name_plural': "United Kingdom Bonds' Static Info",
            },
        ),
        migrations.CreateModel(
            name='USBondStaticInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=18)),
                ('long_name', models.CharField(max_length=32)),
                ('country', models.CharField(choices=[('G', 'Global'), ('US', 'United States of America'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], default='US', max_length=2)),
                ('market', models.CharField(choices=[('NYSE', 'New York Stock Exchange (NYSE)'), ('NASDAQ', 'NASDAQ Stock Market'), ('OTC Markets', 'Over-The-Counter Markets (OTC)'), ('AMEX', 'American Stock Exchange (AMEX)'), ('BSE', 'Boston Stock Exchange (BSE)'), ('CBOE', 'Chicago Board Options Exchange (CBOE)'), ('CBOT', 'Chicago Board of Trade (CBOT)'), ('CME', 'Chicago Mercantile Exchange (CME)'), ('CHX', 'Chicago Stock Exchange (CHX)'), ('ISE', 'International Securities Exchange i.nameSE)'), ('MS4X', 'Miami Stock Exchange (MS4X)'), ('NSX', 'National Stock Exchange (NSX)'), ('PHLX', 'Philadelphia Stock Exchange (PHLX)'), ('NYSE Arca', 'NYSE Arca')], max_length=11)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('JPY', 'Japanese Yen'), ('GBP', 'Pound Sterling'), ('HKD', 'Hong Kong Dollar'), ('CNY', 'Chinese Yuan'), ('CAD', 'Canadian Dollar'), ('EUR', 'Euro'), ('AUD', 'Australian Dollar')], default='USD', max_length=3)),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name': "United States Bonds' Static Info",
                'verbose_name_plural': "United States Bonds' Static Info",
            },
        ),
        migrations.AlterModelOptions(
            name='hketfstaticinfo',
            options={'verbose_name': "Hong Kong ETFs' Static Info", 'verbose_name_plural': "Hong Kong ETFs' Static Info"},
        ),
    ]
