# Generated by Django 2.2.7 on 2019-12-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0067_fundissuers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundissuers',
            name='name',
            field=models.CharField(max_length=55),
        ),
    ]
