# Generated by Django 2.2.7 on 2019-12-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0068_auto_20191226_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='AustraliaFundStaticInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=13)),
                ('long_name', models.CharField(max_length=28)),
                ('country', models.CharField(choices=[('G', 'Global'), ('US', 'United States of America'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], default='AU', max_length=2)),
                ('market', models.CharField(choices=[('ASX', 'Australian Securities Exchange')], default='ASX', max_length=3)),
                ('link', models.URLField()),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('JPY', 'Japanese Yen'), ('GBP', 'Pound Sterling'), ('HKD', 'Hong Kong Dollar'), ('CNY', 'Chinese Yuan'), ('CAD', 'Canadian Dollar'), ('EUR', 'Euro'), ('AUD', 'Australian Dollar')], default='AUD', max_length=3)),
                ('issuer', models.CharField(choices=[('T. Rowe Price International Limited', 'T. Rowe Price International Limited'), ('Vanguard Investments Australia Ltd', 'Vanguard Investments Australia Ltd'), ('Antipodes Partners Limited', 'Antipodes Partners Limited'), ('IOOF Group', 'IOOF Group'), ('VicSuper Pty Ltd', 'VicSuper Pty Ltd'), ('DFA Australia Limited', 'DFA Australia Limited'), ('Aberdeen Standard Investments', 'Aberdeen Standard Investments'), ('FIL Australia', 'FIL Australia'), ('PIMCO Australia Pty Limited', 'PIMCO Australia Pty Limited'), ('Electricity Supply Industry Super (Qld)', 'Electricity Supply Industry Super (Qld)'), ('Bennelong Funds Management Ltd', 'Bennelong Funds Management Ltd'), ('Vanguard', 'Vanguard'), ('AustralianSuper Pty Ltd', 'AustralianSuper Pty Ltd'), ('Commonwealth/Colonial Group', 'Commonwealth/Colonial Group'), ('Magellan Asset Management Limited', 'Magellan Asset Management Limited'), ('Sunsuper Pty Ltd', 'Sunsuper Pty Ltd'), ('Russell Investment Management Limited', 'Russell Investment Management Limited'), ('National/MLC Group', 'National/MLC Group'), ('Ellerston Capital Limited', 'Ellerston Capital Limited'), ('Macquarie Bank Group', 'Macquarie Bank Group'), ('Paradice Investment Management Pty Ltd', 'Paradice Investment Management Pty Ltd'), ('Challenger Ltd', 'Challenger Ltd'), ('Investors Mutual Limited', 'Investors Mutual Limited'), ('State Street Global Advisors (Aus) Ltd', 'State Street Global Advisors (Aus) Ltd'), ('AMP Group', 'AMP Group'), ('Janus Henderson Group PLC', 'Janus Henderson Group PLC'), ('MFS Investment Management', 'MFS Investment Management'), ('Retail Employees Superannuation Pty Ltd', 'Retail Employees Superannuation Pty Ltd')], max_length=39)),
                ('isin', models.CharField(max_length=12)),
                ('min_investment', models.CharField(max_length=15)),
                ('category', models.CharField(max_length=30)),
                ('inception_date', models.CharField(max_length=12)),
            ],
            options={
                'verbose_name': "Australia Funds' Static Info",
                'verbose_name_plural': "Australia Funds' Static Info",
            },
        ),
        migrations.CreateModel(
            name='CanadaFundStaticInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=10)),
                ('long_name', models.CharField(max_length=25)),
                ('country', models.CharField(choices=[('G', 'Global'), ('US', 'United States of America'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], default='CA', max_length=2)),
                ('market', models.CharField(choices=[('NEO', 'Aequitas Neo Exchange (NEO)'), ('Toronto', 'Toronto Stock Exchange (TSX)'), ('CSE', 'Canadian Securities Exchange (CSE)'), ('NASDAQ', 'NASDAQ Canada'), ('TSXV', 'TSX Venture Exchange (TSXV)')], max_length=7)),
                ('link', models.URLField()),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('JPY', 'Japanese Yen'), ('GBP', 'Pound Sterling'), ('HKD', 'Hong Kong Dollar'), ('CNY', 'Chinese Yuan'), ('CAD', 'Canadian Dollar'), ('EUR', 'Euro'), ('AUD', 'Australian Dollar')], default='CAD', max_length=3)),
                ('issuer', models.CharField(choices=[('Capital International Asset Mngmt', 'Capital International Asset Mngmt'), ('TD Asset Management Inc', 'TD Asset Management Inc'), ('Investors Group Inc', 'Investors Group Inc'), ('PIMCO Canada', 'PIMCO Canada'), ('Scotia Asset Management', 'Scotia Asset Management'), ('Fidelity Investments Canada ULC', 'Fidelity Investments Canada ULC'), ('Manulife Investments', 'Manulife Investments'), ('EdgePoint Wealth Management Inc', 'EdgePoint Wealth Management Inc'), ('RBC Global Asset Management Inc.', 'RBC Global Asset Management Inc.')], max_length=33)),
                ('isin', models.CharField(max_length=12)),
                ('min_investment', models.CharField(max_length=15)),
                ('category', models.CharField(max_length=30)),
                ('inception_date', models.CharField(max_length=12)),
            ],
            options={
                'verbose_name': "Canada Funds' Static Info",
                'verbose_name_plural': "Canada Funds' Static Info",
            },
        ),
        migrations.CreateModel(
            name='ChinaFundStaticInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=9)),
                ('long_name', models.CharField(max_length=24)),
                ('country', models.CharField(choices=[('G', 'Global'), ('US', 'United States of America'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], default='CH', max_length=2)),
                ('market', models.CharField(choices=[('Shanghai', 'Shanghai Stock Exchange'), ('Shenzhen', 'Shenzhen Stock Exchange')], max_length=20)),
                ('link', models.URLField()),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('JPY', 'Japanese Yen'), ('GBP', 'Pound Sterling'), ('HKD', 'Hong Kong Dollar'), ('CNY', 'Chinese Yuan'), ('CAD', 'Canadian Dollar'), ('EUR', 'Euro'), ('AUD', 'Australian Dollar')], default='CNY', max_length=3)),
                ('issuer', models.CharField(choices=[('China Asset Mgmt Co.,Ltd', 'China Asset Mgmt Co.,Ltd'), ('China Universal Asset Mgmt Co.Ltd', 'China Universal Asset Mgmt Co.Ltd'), ('Penghua Fund Mgmt Co.,Ltd', 'Penghua Fund Mgmt Co.,Ltd'), ('Harvest Fund Mgmt Co.,Ltd', 'Harvest Fund Mgmt Co.,Ltd'), ('ABC-CA Fund Mgmt Co.,Ltd', 'ABC-CA Fund Mgmt Co.,Ltd'), ('BOC International China Ltd', 'BOC International China Ltd'), ('GF Fund Mgmt Co.,Ltd', 'GF Fund Mgmt Co.,Ltd'), ('E Fund Mgmt Co.,Ltd', 'E Fund Mgmt Co.,Ltd'), ('Tian Hong Asset Mgmt Co.,Ltd', 'Tian Hong Asset Mgmt Co.,Ltd'), ('AXA SPDB Investment Managers Co.,Ltd', 'AXA SPDB Investment Managers Co.,Ltd'), ('Invesco Great Wall Fund Mgmt Co. Ltd', 'Invesco Great Wall Fund Mgmt Co. Ltd'), ('Great Wall Fund Mgmt Co.,Ltd', 'Great Wall Fund Mgmt Co.,Ltd'), ('ZhongRong Fund Management Co.,Ltd', 'ZhongRong Fund Management Co.,Ltd'), ('Lion Fund Mgmt Co.,Ltd', 'Lion Fund Mgmt Co.,Ltd'), ('Lombarda China Fund Mgmt Co.,Ltd', 'Lombarda China Fund Mgmt Co.,Ltd'), ('HuaAn Fund Mgmt Co., Ltd', 'HuaAn Fund Mgmt Co., Ltd'), ('Bank of China Investment Mgmt Co.,Ltd', 'Bank of China Investment Mgmt Co.,Ltd'), ('Fullgoal Fund Mgmt Co.,Ltd', 'Fullgoal Fund Mgmt Co.,Ltd'), ('Bank of Communications Schroders', 'Bank of Communications Schroders'), ('Yinhua Fund Mgmt Co., Ltd', 'Yinhua Fund Mgmt Co., Ltd'), ('Ping An Fund Management Company Limited', 'Ping An Fund Management Company Limited'), ('China International Fund Mgmt Co.,Ltd', 'China International Fund Mgmt Co.,Ltd'), ('AEGON-Industrial Fund Mgmt Co.,Ltd', 'AEGON-Industrial Fund Mgmt Co.,Ltd'), ('CCB Principal Asset Mgmt Co.,Ltd', 'CCB Principal Asset Mgmt Co.,Ltd'), ('Rongtong Fund Mgmt Co.,Ltd', 'Rongtong Fund Mgmt Co.,Ltd'), ('CIB Fund Management Co.,Ltd', 'CIB Fund Management Co.,Ltd'), ('ICBC Credit Suisse Asset Mgmt Co.,Ltd', 'ICBC Credit Suisse Asset Mgmt Co.,Ltd'), ('Bosera Asset Management Co., Limited', 'Bosera Asset Management Co., Limited'), ('Hwabao WP Fund Management Co.,Ltd', 'Hwabao WP Fund Management Co.,Ltd'), ('China Merchants Fund Mgmt Co.,Ltd', 'China Merchants Fund Mgmt Co.,Ltd'), ('China Southern Fund Mgmt Co.,Ltd', 'China Southern Fund Mgmt Co.,Ltd')], max_length=39)),
                ('isin', models.CharField(max_length=12)),
                ('min_investment', models.CharField(max_length=15)),
                ('category', models.CharField(max_length=30)),
                ('inception_date', models.CharField(max_length=12)),
            ],
            options={
                'verbose_name': "China Funds' Static Info",
                'verbose_name_plural': "China Funds' Static Info",
            },
        ),
        migrations.CreateModel(
            name='GermanyFundStaticInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=11)),
                ('long_name', models.CharField(max_length=26)),
                ('country', models.CharField(choices=[('G', 'Global'), ('US', 'United States of America'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], default='GE', max_length=2)),
                ('market', models.CharField(choices=[('Frankfurt', 'Frankfurt Stock Exchange (XFRA)'), ('Berlin', 'Berlin Stock Exchange (XBER)'), ('Xetra', 'Xetra Stock Exchange (XETR)'), ('Munich', 'Munich Stock Exchange (XMUN)'), ('Stuttgart', 'Stuttgart Stock Exchange (XSTU)'), ('Dusseldorf', 'Dusseldorf Stock Exchange(XDUS)'), ('Hamburg', 'Hamburg Stock Exchange(XHAM)'), ('Hannover', 'Hannover Stock Exchange (XHAN)')], max_length=20)),
                ('link', models.URLField()),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('JPY', 'Japanese Yen'), ('GBP', 'Pound Sterling'), ('HKD', 'Hong Kong Dollar'), ('CNY', 'Chinese Yuan'), ('CAD', 'Canadian Dollar'), ('EUR', 'Euro'), ('AUD', 'Australian Dollar')], default='EUR', max_length=3)),
                ('issuer', models.CharField(choices=[('Axxion S.A.', 'Axxion S.A.'), ('FRANKFURT-TRUST Investment-GmbH', 'FRANKFURT-TRUST Investment-GmbH'), ('M&G Securities Ltd', 'M&G Securities Ltd'), ('Universal-Investment GmbH', 'Universal-Investment GmbH'), ('Union Investment Real Estate GmbH', 'Union Investment Real Estate GmbH'), ('DWS Investment GmbH', 'DWS Investment GmbH'), ('AXA Investment Managers Deutschland GmbH', 'AXA Investment Managers Deutschland GmbH'), ('Deutsche Asset Management Investment GmbH', 'Deutsche Asset Management Investment GmbH'), ('RREEF Investment GmbH', 'RREEF Investment GmbH'), ('UBS Fund Management (Luxembourg) S.A.', 'UBS Fund Management (Luxembourg) S.A.'), ('Savills Fund Management GmbH', 'Savills Fund Management GmbH'), ('DWS Investment S.A.', 'DWS Investment S.A.'), ('Deka Vermögensmanagement GmbH', 'Deka Vermögensmanagement GmbH'), ('Wellington Management Company LLP', 'Wellington Management Company LLP'), ('Comgest Asset Management Intl Ltd', 'Comgest Asset Management Intl Ltd'), ('Deka Investment GmbH', 'Deka Investment GmbH'), ('Commerz Real Investment GmbH', 'Commerz Real Investment GmbH'), ('Allianz Global Investors GmbH', 'Allianz Global Investors GmbH'), ('DWS Grundbesitz GmbH', 'DWS Grundbesitz GmbH'), ('Deka Immobilien Investment GmbH', 'Deka Immobilien Investment GmbH'), ('Westlnvest GmbH', 'Westlnvest GmbH'), ('Union Investment Privatfonds GmbH', 'Union Investment Privatfonds GmbH')], max_length=41)),
                ('isin', models.CharField(max_length=12)),
                ('min_investment', models.CharField(max_length=15)),
                ('category', models.CharField(max_length=30)),
                ('inception_date', models.CharField(max_length=12)),
            ],
            options={
                'verbose_name': "Germany Funds' Static Info",
                'verbose_name_plural': "Germany Funds' Static Info",
            },
        ),
        migrations.CreateModel(
            name='HKFundStaticInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=13)),
                ('long_name', models.CharField(max_length=28)),
                ('country', models.CharField(choices=[('G', 'Global'), ('US', 'United States of America'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], default='HK', max_length=2)),
                ('market', models.CharField(choices=[('HKG', 'The Stock Exchange of Hong Kong Limited')], default='HKG', max_length=3)),
                ('link', models.URLField()),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('JPY', 'Japanese Yen'), ('GBP', 'Pound Sterling'), ('HKD', 'Hong Kong Dollar'), ('CNY', 'Chinese Yuan'), ('CAD', 'Canadian Dollar'), ('EUR', 'Euro'), ('AUD', 'Australian Dollar')], default='HKD', max_length=3)),
                ('issuer', models.CharField(choices=[('Pictet Asset Management (Europe) SA', 'Pictet Asset Management (Europe) SA'), ('PineBridge Investments Hong Kong Limited', 'PineBridge Investments Hong Kong Limited'), ('BOCI-Prudential Asset Management', 'BOCI-Prudential Asset Management'), ('Schroder Investment Management Lux S.A.', 'Schroder Investment Management Lux S.A.'), ('BOCI-Prudential Trustee Limited', 'BOCI-Prudential Trustee Limited'), ('AllianceBernstein (Luxembourg) S.à r.l.', 'AllianceBernstein (Luxembourg) S.à r.l.'), ('Zeal Asset Management Limited', 'Zeal Asset Management Limited'), ('Franklin Templeton International Services S.à r.l.', 'Franklin Templeton International Services S.à r.l.'), ('RCM Asia Pacific Limited', 'RCM Asia Pacific Limited'), ('Janus Henderson Investors', 'Janus Henderson Investors'), ('UBS Fund Management (Luxembourg) S.A.', 'UBS Fund Management (Luxembourg) S.A.'), ('Fidelity (FIL Inv Mgmt (Lux) S.A.)', 'Fidelity (FIL Inv Mgmt (Lux) S.A.)'), ('HSBC Life (International) Limited', 'HSBC Life (International) Limited'), ('Franklin Templeton Investment Funds', 'Franklin Templeton Investment Funds'), ('JPMorgan Funds (Asia) Limited', 'JPMorgan Funds (Asia) Limited'), ('HSBC Investment Funds (Luxembourg) S.A.', 'HSBC Investment Funds (Luxembourg) S.A.'), ('BEA Union Investment Management Ltd', 'BEA Union Investment Management Ltd'), ('PIMCO Global Advisors (Ireland) Limited', 'PIMCO Global Advisors (Ireland) Limited'), ('Manulife Asset Management (HK) Ltd', 'Manulife Asset Management (HK) Ltd'), ('Sun Life Hong Kong Limited', 'Sun Life Hong Kong Limited'), ('Schroder Investment Management (HK) Ltd', 'Schroder Investment Management (HK) Ltd'), ('Bank Consortium', 'Bank Consortium'), ('BlackRock (Luxembourg) SA', 'BlackRock (Luxembourg) SA'), ('Hang Seng Investment Management Ltd', 'Hang Seng Investment Management Ltd'), ('AIA Company (Trustee) Limited', 'AIA Company (Trustee) Limited'), ('Value Partners Hong Kong Limited', 'Value Partners Hong Kong Limited'), ('Allianz Global Investors GmbH', 'Allianz Global Investors GmbH'), ('Invesco Hong Kong Limited', 'Invesco Hong Kong Limited'), ('Principal Trust Company (Asia) Limited', 'Principal Trust Company (Asia) Limited'), ('HSBC Investment Funds (HK) Limited', 'HSBC Investment Funds (HK) Limited'), ('JPMorgan Asset Management (Europe) S.à r.l.', 'JPMorgan Asset Management (Europe) S.à r.l.'), ('FIL Investment Management (HK) Ltd', 'FIL Investment Management (HK) Ltd')], max_length=50)),
                ('isin', models.CharField(max_length=12)),
                ('min_investment', models.CharField(max_length=15)),
                ('category', models.CharField(max_length=30)),
                ('inception_date', models.CharField(max_length=12)),
            ],
            options={
                'verbose_name': "Hong Kong Funds' Static Info",
                'verbose_name_plural': "Hong Kong Funds' Static Info",
            },
        ),
        migrations.CreateModel(
            name='JapanFundStaticInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=10)),
                ('long_name', models.CharField(max_length=24)),
                ('country', models.CharField(choices=[('G', 'Global'), ('US', 'United States of America'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], default='JP', max_length=2)),
                ('market', models.CharField(choices=[('Tokyo', 'Tokyo Stock Exchange (TYO)'), ('Osaka', 'Osaka Securities Exchange'), ('Nagoya', 'Nagoya Stock Exchange (NSE)'), ('Fukuoka', 'Fukuoka Stock Exchange (FSE)'), ('Sapporo', 'Sapporo Securities Exchange'), ('JASDAQ', 'JASDAQ Securities Exchange')], max_length=7)),
                ('link', models.URLField()),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('JPY', 'Japanese Yen'), ('GBP', 'Pound Sterling'), ('HKD', 'Hong Kong Dollar'), ('CNY', 'Chinese Yuan'), ('CAD', 'Canadian Dollar'), ('EUR', 'Euro'), ('AUD', 'Australian Dollar')], default='JPY', max_length=3)),
                ('issuer', models.CharField(choices=[('Rheos Capital Works Inc', 'Rheos Capital Works Inc'), ('AllianceBernstein Japan Ltd', 'AllianceBernstein Japan Ltd'), ('Mitsubishi UFJ Kokusai Asst Mgmt Co.,Ltd', 'Mitsubishi UFJ Kokusai Asst Mgmt Co.,Ltd'), ('Goldman Sachs Asset Management Co Ltd', 'Goldman Sachs Asset Management Co Ltd'), ('Nomura Asset Management Co Ltd', 'Nomura Asset Management Co Ltd'), ('JPMorgan Asset Management (Japan) Ltd', 'JPMorgan Asset Management (Japan) Ltd'), ('Asset Management One Co., Ltd.', 'Asset Management One Co., Ltd.'), ('Shinkin Asset Management Co Ltd', 'Shinkin Asset Management Co Ltd'), ('Pictet Asset Management (Japan) Ltd', 'Pictet Asset Management (Japan) Ltd'), ('Nikko Asset Management Co Ltd', 'Nikko Asset Management Co Ltd'), ('Sumitomo Mitsui Trust Ast Mgmt Co Ltd', 'Sumitomo Mitsui Trust Ast Mgmt Co Ltd'), ('Daiwa SB Investments Ltd.', 'Daiwa SB Investments Ltd.'), ('Nissay Asset Management Corporation', 'Nissay Asset Management Corporation'), ('Tokio Marine Asset Management Co Ltd', 'Tokio Marine Asset Management Co Ltd'), ('FIL Investments (Japan) Limited', 'FIL Investments (Japan) Limited'), ('Sumitomo Mitsui DS Asset Management Company', 'Sumitomo Mitsui DS Asset Management Company'), ('Okasan Asset Management Co Ltd', 'Okasan Asset Management Co Ltd'), ('Legg Mason Asset Mgmt (Japan) Co Ltd', 'Legg Mason Asset Mgmt (Japan) Co Ltd'), ('UBS Asset Management (Japan) Ltd', 'UBS Asset Management (Japan) Ltd'), ('Sumitomo Mitsui Trust Asset Management Co., Ltd.', 'Sumitomo Mitsui Trust Asset Management Co., Ltd.'), ('Daiwa Asset Management Co Ltd', 'Daiwa Asset Management Co Ltd'), ('Sawakami Asset Management Inc', 'Sawakami Asset Management Inc'), ('JP Asset Management Co.,Ltd.', 'JP Asset Management Co.,Ltd.'), ('Saison Asset Management Co Ltd', 'Saison Asset Management Co Ltd')], max_length=48)),
                ('isin', models.CharField(max_length=12)),
                ('min_investment', models.CharField(max_length=15)),
                ('category', models.CharField(max_length=30)),
                ('inception_date', models.CharField(max_length=12)),
            ],
            options={
                'verbose_name': "Japan Funds' Static Info",
                'verbose_name_plural': "Japan Funds' Static Info",
            },
        ),
        migrations.CreateModel(
            name='UKFundStaticInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=8)),
                ('long_name', models.CharField(max_length=33)),
                ('country', models.CharField(choices=[('G', 'Global'), ('US', 'United States of America'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], default='UK', max_length=2)),
                ('market', models.CharField(choices=[('London', 'London Stock Exchange')], default='London', max_length=20)),
                ('link', models.URLField()),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('JPY', 'Japanese Yen'), ('GBP', 'Pound Sterling'), ('HKD', 'Hong Kong Dollar'), ('CNY', 'Chinese Yuan'), ('CAD', 'Canadian Dollar'), ('EUR', 'Euro'), ('AUD', 'Australian Dollar')], default='GBP', max_length=3)),
                ('issuer', models.CharField(choices=[('Pictet Asset Management (Europe) SA', 'Pictet Asset Management (Europe) SA'), ('Royal London Asset Management Ltd', 'Royal London Asset Management Ltd'), ('M&G Securities Ltd', 'M&G Securities Ltd'), ('UBP Asset Management (Europe) S.A.', 'UBP Asset Management (Europe) S.A.'), ('Vanguard Group (Ireland) Limited', 'Vanguard Group (Ireland) Limited'), ('Lindsell Train Ltd', 'Lindsell Train Ltd'), ('Invesco Fund Managers Limited', 'Invesco Fund Managers Limited'), ('Franklin Templeton Investment Funds', 'Franklin Templeton Investment Funds'), ('PineBridge Investments Ireland Ltd', 'PineBridge Investments Ireland Ltd'), ('Fundsmith LLP', 'Fundsmith LLP'), ('BlackRock Fund Managers Limited', 'BlackRock Fund Managers Limited'), ('PIMCO Global Advisors (Ireland) Limited', 'PIMCO Global Advisors (Ireland) Limited'), ('First State Investment Mgmt (UK) Ltd', 'First State Investment Mgmt (UK) Ltd'), ('Legal & General(Unit Trust Managers)Ltd', 'Legal & General(Unit Trust Managers)Ltd'), ('BlackRock Asset Management Ireland Ltd', 'BlackRock Asset Management Ireland Ltd'), ('Jupiter Unit Trust Managers Ltd', 'Jupiter Unit Trust Managers Ltd'), ('Capital Group', 'Capital Group'), ('Tokio Marine Asset Management Co Ltd', 'Tokio Marine Asset Management Co Ltd'), ('Morgan Stanley Investment Management (ACD) Limited', 'Morgan Stanley Investment Management (ACD) Limited'), ('Vanguard Investments UK, Limited', 'Vanguard Investments UK, Limited'), ('Russell Investments Ireland Limited', 'Russell Investments Ireland Limited'), ('Nordea Investment Funds SA', 'Nordea Investment Funds SA'), ('JPMorgan Asset Management (Europe) S.à r.l.', 'JPMorgan Asset Management (Europe) S.à r.l.')], max_length=50)),
                ('isin', models.CharField(max_length=12)),
                ('min_investment', models.CharField(max_length=15)),
                ('category', models.CharField(max_length=30)),
                ('inception_date', models.CharField(max_length=12)),
            ],
            options={
                'verbose_name': "United Kingdom Funds' Static Info",
                'verbose_name_plural': "United Kingdom Funds' Static Info",
            },
        ),
        migrations.CreateModel(
            name='USFundStaticInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=18)),
                ('long_name', models.CharField(max_length=32)),
                ('country', models.CharField(choices=[('G', 'Global'), ('US', 'United States of America'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], default='US', max_length=2)),
                ('market', models.CharField(choices=[('NYSE', 'New York Stock Exchange (NYSE)'), ('NASDAQ', 'NASDAQ Stock Market'), ('OTC Markets', 'Over-The-Counter Markets (OTC)'), ('AMEX', 'American Stock Exchange (AMEX)'), ('BSE', 'Boston Stock Exchange (BSE)'), ('CBOE', 'Chicago Board Options Exchange (CBOE)'), ('CBOT', 'Chicago Board of Trade (CBOT)'), ('CME', 'Chicago Mercantile Exchange (CME)'), ('CHX', 'Chicago Stock Exchange (CHX)'), ('ISE', 'International Securities Exchange i.nameSE)'), ('MS4X', 'Miami Stock Exchange (MS4X)'), ('NSX', 'National Stock Exchange (NSX)'), ('PHLX', 'Philadelphia Stock Exchange (PHLX)'), ('NYSE Arca', 'NYSE Arca')], max_length=11)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('JPY', 'Japanese Yen'), ('GBP', 'Pound Sterling'), ('HKD', 'Hong Kong Dollar'), ('CNY', 'Chinese Yuan'), ('CAD', 'Canadian Dollar'), ('EUR', 'Euro'), ('AUD', 'Australian Dollar')], default='USD', max_length=3)),
                ('link', models.URLField()),
                ('issuer', models.CharField(choices=[('American Funds', 'American Funds'), ('Dimensional Fund Advisors', 'Dimensional Fund Advisors'), ('First Eagle', 'First Eagle'), ('Pimco', 'Pimco'), ('Fidelity Management Trust Co', 'Fidelity Management Trust Co'), ('T. Rowe Price', 'T. Rowe Price'), ('DoubleLine', 'DoubleLine'), ('State Street Global Advisors', 'State Street Global Advisors'), ('Metropolitan West Funds', 'Metropolitan West Funds'), ('Dodge & Cox', 'Dodge & Cox'), ('Schwab Funds', 'Schwab Funds'), ('Mellon Investments Corporation', 'Mellon Investments Corporation'), ('Franklin Templeton Investments', 'Franklin Templeton Investments'), ('Fidelity Investments', 'Fidelity Investments'), ('Vanguard', 'Vanguard')], max_length=30)),
                ('isin', models.CharField(max_length=12)),
                ('min_investment', models.CharField(max_length=15)),
                ('category', models.CharField(max_length=30)),
                ('inception_date', models.CharField(max_length=12)),
            ],
            options={
                'verbose_name': "United States Funds' Static Info",
                'verbose_name_plural': "United States Funds' Static Info",
            },
        ),
    ]
