# Generated by Django 2.2.7 on 2019-12-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0069_australiafundstaticinfo_canadafundstaticinfo_chinafundstaticinfo_germanyfundstaticinfo_hkfundstatici'),
    ]

    operations = [
        migrations.AlterField(
            model_name='australiafundstaticinfo',
            name='min_investment',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='canadafundstaticinfo',
            name='min_investment',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='chinafundstaticinfo',
            name='min_investment',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='germanyfundstaticinfo',
            name='min_investment',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='hkfundstaticinfo',
            name='min_investment',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='japanfundstaticinfo',
            name='min_investment',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='ukfundstaticinfo',
            name='min_investment',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='usfundstaticinfo',
            name='inception_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='usfundstaticinfo',
            name='min_investment',
            field=models.IntegerField(max_length=10),
        ),
    ]
