# Generated by Django 2.2.7 on 2019-12-26 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0070_auto_20191226_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usfundstaticinfo',
            name='inception_date',
        ),
    ]
