# Generated by Django 2.2.7 on 2019-12-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0071_remove_usfundstaticinfo_inception_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='usfundstaticinfo',
            name='inception_date',
            field=models.CharField(default=None, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usfundstaticinfo',
            name='inception_date1',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usfundstaticinfo',
            name='inception_date2',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='australiafundstaticinfo',
            name='min_investment',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='canadafundstaticinfo',
            name='min_investment',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='chinafundstaticinfo',
            name='min_investment',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='germanyfundstaticinfo',
            name='min_investment',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hkfundstaticinfo',
            name='min_investment',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='japanfundstaticinfo',
            name='min_investment',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ukfundstaticinfo',
            name='min_investment',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usfundstaticinfo',
            name='min_investment',
            field=models.IntegerField(),
        ),
    ]
