# Generated by Django 2.2.7 on 2019-12-26 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0072_auto_20191226_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usfundstaticinfo',
            name='inception_date',
        ),
        migrations.RemoveField(
            model_name='usfundstaticinfo',
            name='inception_date1',
        ),
        migrations.RemoveField(
            model_name='usfundstaticinfo',
            name='inception_date2',
        ),
    ]
