# Generated by Django 2.2.7 on 2019-12-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0074_auto_20191226_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='australiafundstaticinfo',
            name='long_name',
            field=models.CharField(max_length=62),
        ),
        migrations.AlterField(
            model_name='australiafundstaticinfo',
            name='short_name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='canadafundstaticinfo',
            name='long_name',
            field=models.CharField(max_length=57),
        ),
        migrations.AlterField(
            model_name='chinafundstaticinfo',
            name='long_name',
            field=models.CharField(max_length=47),
        ),
        migrations.AlterField(
            model_name='chinafundstaticinfo',
            name='short_name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='germanyfundstaticinfo',
            name='long_name',
            field=models.CharField(max_length=63),
        ),
        migrations.AlterField(
            model_name='germanyfundstaticinfo',
            name='short_name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='hkfundstaticinfo',
            name='long_name',
            field=models.CharField(max_length=93),
        ),
        migrations.AlterField(
            model_name='hkfundstaticinfo',
            name='short_name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='japanfundstaticinfo',
            name='long_name',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='ukfundstaticinfo',
            name='long_name',
            field=models.CharField(max_length=91),
        ),
        migrations.AlterField(
            model_name='ukfundstaticinfo',
            name='short_name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='usfundstaticinfo',
            name='long_name',
            field=models.CharField(max_length=78),
        ),
        migrations.AlterField(
            model_name='usfundstaticinfo',
            name='short_name',
            field=models.CharField(max_length=10),
        ),
    ]
