# Generated by Django 2.2.7 on 2019-12-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0075_auto_20191227_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='australiafundstaticinfo',
            name='category_descrptn',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='canadafundstaticinfo',
            name='category_descrptn',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='chinafundstaticinfo',
            name='category_descrptn',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='germanyfundstaticinfo',
            name='category_descrptn',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='hkfundstaticinfo',
            name='category_descrptn',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='japanfundstaticinfo',
            name='category_descrptn',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='ukfundstaticinfo',
            name='category_descrptn',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='usfundstaticinfo',
            name='category_descrptn',
            field=models.CharField(default='', max_length=256),
        ),
    ]
