# Generated by Django 2.2.7 on 2019-12-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0078_auto_20191227_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ukfundstaticinfo',
            name='category',
            field=models.CharField(max_length=40),
        ),
    ]
