# Generated by Django 2.2.7 on 2019-12-27 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0081_auto_20191227_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usfundstaticinfo',
            name='inception_date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
