# Generated by Django 2.2.7 on 2019-12-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0083_auto_20191227_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hkfundstaticinfo',
            name='category',
            field=models.CharField(max_length=45),
        ),
    ]
