# Generated by Django 2.2.7 on 2019-12-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0084_auto_20191227_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='australiafundstaticinfo',
            name='category_descrptn',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='canadafundstaticinfo',
            name='category_descrptn',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='chinafundstaticinfo',
            name='category_descrptn',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='germanyfundstaticinfo',
            name='category_descrptn',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='hkfundstaticinfo',
            name='category_descrptn',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='hkfundstaticinfo',
            name='isin',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='japanfundstaticinfo',
            name='category_descrptn',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ukfundstaticinfo',
            name='category_descrptn',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='usfundstaticinfo',
            name='category_descrptn',
            field=models.TextField(null=True),
        ),
    ]
