# Generated by Django 2.2.7 on 2019-12-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0088_auto_20191227_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='germanyfundstaticinfo',
            name='category',
            field=models.CharField(max_length=41),
        ),
    ]
