# Generated by Django 2.2.7 on 2019-12-28 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0089_auto_20191227_1933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='australiabondstaticinfo',
            options={'verbose_name': "(Static Info) Australia Bonds'", 'verbose_name_plural': "(Static Info) Australia Bonds'"},
        ),
        migrations.AlterModelOptions(
            name='australiaetfstaticinfo',
            options={'verbose_name': "(Static Info) Australia ETFs'", 'verbose_name_plural': "(Static Info) Australia ETFs'"},
        ),
        migrations.AlterModelOptions(
            name='australiafundstaticinfo',
            options={'verbose_name': "(Static Info) Australia Funds'", 'verbose_name_plural': "(Static Info) Australia Funds'"},
        ),
        migrations.AlterModelOptions(
            name='australiaindexstaticinfo',
            options={'verbose_name': '(Static Info) Australia Indices', 'verbose_name_plural': '(Static Info) Australia Indices'},
        ),
        migrations.AlterModelOptions(
            name='australiastockstaticinfo',
            options={'verbose_name': '(Static Info) Australia Stocks', 'verbose_name_plural': '(Static Info) Australia Stocks'},
        ),
        migrations.AlterModelOptions(
            name='canadabondstaticinfo',
            options={'verbose_name': "(Static Info) Canada Bonds'", 'verbose_name_plural': "(Static Info) Canada Bonds'"},
        ),
        migrations.AlterModelOptions(
            name='canadaetfstaticinfo',
            options={'verbose_name': "(Static Info) Canada ETFs'", 'verbose_name_plural': "(Static Info) Canada ETFs'"},
        ),
        migrations.AlterModelOptions(
            name='canadafundstaticinfo',
            options={'verbose_name': "(Static Info) Canada Funds'", 'verbose_name_plural': "(Static Info) Canada Funds'"},
        ),
        migrations.AlterModelOptions(
            name='canadaindexstaticinfo',
            options={'verbose_name': '(Static Info) Canada Indices', 'verbose_name_plural': '(Static Info) Canada Indices'},
        ),
        migrations.AlterModelOptions(
            name='canadastockstaticinfo',
            options={'verbose_name': '(Static Info) Canada Stocks', 'verbose_name_plural': '(Static Info) Canada Stocks'},
        ),
        migrations.AlterModelOptions(
            name='chinabondstaticinfo',
            options={'verbose_name': "(Static Info) China Bonds'", 'verbose_name_plural': "(Static Info) China Bonds'"},
        ),
        migrations.AlterModelOptions(
            name='chinaetfstaticinfo',
            options={'verbose_name': "(Static Info) China ETFs'", 'verbose_name_plural': "(Static Info) China ETFs'"},
        ),
        migrations.AlterModelOptions(
            name='chinafundstaticinfo',
            options={'verbose_name': "(Static Info) China Funds'", 'verbose_name_plural': "(Static Info) China Funds'"},
        ),
        migrations.AlterModelOptions(
            name='chinaindexstaticinfo',
            options={'verbose_name': '(Static Info) China Indices', 'verbose_name_plural': '(Static Info) China Indices'},
        ),
        migrations.AlterModelOptions(
            name='chinastockstaticinfo',
            options={'verbose_name': '(Static Info) China Stocks', 'verbose_name_plural': '(Static Info) China Stocks'},
        ),
        migrations.AlterModelOptions(
            name='commoditystaticinfo',
            options={'verbose_name': "(Static Info) Commodities'", 'verbose_name_plural': "(Static Info) Commodities'"},
        ),
        migrations.AlterModelOptions(
            name='cryptocurrencystaticinfo',
            options={'verbose_name': "(Static Info) Cryptocurrencies'", 'verbose_name_plural': "(Static Info) Cryptocurrencies'"},
        ),
        migrations.AlterModelOptions(
            name='currencystaticinfo',
            options={'verbose_name': "(Static Info) Currencies'", 'verbose_name_plural': "(Static Info) Currencies'"},
        ),
        migrations.AlterModelOptions(
            name='etfissuers',
            options={'verbose_name': '(Static Info) ETF Issuers', 'verbose_name_plural': '(Static Info) ETF Issuers'},
        ),
        migrations.AlterModelOptions(
            name='fundissuers',
            options={'verbose_name': '(Static Info) Fund Issuers', 'verbose_name_plural': '(Static Info) Fund Issuers'},
        ),
        migrations.AlterModelOptions(
            name='germanybondstaticinfo',
            options={'verbose_name': "(Static Info) Germany Bonds'", 'verbose_name_plural': "(Static Info) Germany Bonds'"},
        ),
        migrations.AlterModelOptions(
            name='germanyetfstaticinfo',
            options={'verbose_name': "(Static Info) Germany ETFs'", 'verbose_name_plural': "(Static Info) Germany ETFs'"},
        ),
        migrations.AlterModelOptions(
            name='germanyfundstaticinfo',
            options={'verbose_name': "(Static Info) Germany Funds'", 'verbose_name_plural': "(Static Info) Germany Funds'"},
        ),
        migrations.AlterModelOptions(
            name='germanyindexstaticinfo',
            options={'verbose_name': '(Static Info) Germany Indices', 'verbose_name_plural': '(Static Info) Germany Indices'},
        ),
        migrations.AlterModelOptions(
            name='germanystockstaticinfo',
            options={'verbose_name': '(Static Info) Germany Stocks', 'verbose_name_plural': '(Static Info) Germany Stocks'},
        ),
        migrations.AlterModelOptions(
            name='hkbondstaticinfo',
            options={'verbose_name': "(Static Info) Hong Kong Bonds'", 'verbose_name_plural': "(Static Info) Hong Kong Bonds'"},
        ),
        migrations.AlterModelOptions(
            name='hketfstaticinfo',
            options={'verbose_name': "(Static Info) Hong Kong ETFs'", 'verbose_name_plural': "(Static Info) Hong Kong ETFs'"},
        ),
        migrations.AlterModelOptions(
            name='hkfundstaticinfo',
            options={'verbose_name': "(Static Info) Hong Kong Funds'", 'verbose_name_plural': "(Static Info) Hong Kong Funds'"},
        ),
        migrations.AlterModelOptions(
            name='hkindexstaticinfo',
            options={'verbose_name': '(Static Info) Hong Kong Indices', 'verbose_name_plural': '(Static Info) Hong Kong Indices'},
        ),
        migrations.AlterModelOptions(
            name='hkstockstaticinfo',
            options={'verbose_name': '(Static Info) Hong Kong Stocks', 'verbose_name_plural': '(Static Info) Hong Kong Stocks'},
        ),
        migrations.AlterModelOptions(
            name='japanbondstaticinfo',
            options={'verbose_name': "(Static Info) Japan Bonds'", 'verbose_name_plural': "(Static Info) Japan Bonds'"},
        ),
        migrations.AlterModelOptions(
            name='japanetfstaticinfo',
            options={'verbose_name': "(Static Info) Japan ETFs'", 'verbose_name_plural': "(Static Info) Japan ETFs'"},
        ),
        migrations.AlterModelOptions(
            name='japanfundstaticinfo',
            options={'verbose_name': "(Static Info) Japan Funds'", 'verbose_name_plural': "(Static Info) Japan Funds'"},
        ),
        migrations.AlterModelOptions(
            name='japanindexstaticinfo',
            options={'verbose_name': '(Static Info) Japan Indices', 'verbose_name_plural': '(Static Info) Japan Indices'},
        ),
        migrations.AlterModelOptions(
            name='japanstockstaticinfo',
            options={'verbose_name': '(Static Info) Japan Stocks', 'verbose_name_plural': '(Static Info) Japan Stocks'},
        ),
        migrations.AlterModelOptions(
            name='ukbondstaticinfo',
            options={'verbose_name': "(Static Info) United Kingdom Bonds'", 'verbose_name_plural': "(Static Info) United Kingdom Bonds'"},
        ),
        migrations.AlterModelOptions(
            name='uketfstaticinfo',
            options={'verbose_name': "(Static Info) United Kingdom ETFs'", 'verbose_name_plural': "(Static Info) United Kingdom ETFs'"},
        ),
        migrations.AlterModelOptions(
            name='ukfundstaticinfo',
            options={'verbose_name': "(Static Info) United Kingdom Funds'", 'verbose_name_plural': "(Static Info) United Kingdom Funds'"},
        ),
        migrations.AlterModelOptions(
            name='ukindexstaticinfo',
            options={'verbose_name': '(Static Info) United Kingdom Indices', 'verbose_name_plural': '(Static Info) United Kingdom Indices'},
        ),
        migrations.AlterModelOptions(
            name='ukstockstaticinfo',
            options={'verbose_name': '(Static Info) United Kingdom Stocks', 'verbose_name_plural': '(Static Info) United Kingdom Stocks'},
        ),
        migrations.AlterModelOptions(
            name='usbondstaticinfo',
            options={'verbose_name': "(Static Info) United States Bonds'", 'verbose_name_plural': "(Static Info) United States Bonds'"},
        ),
        migrations.AlterModelOptions(
            name='usetfstaticinfo',
            options={'verbose_name': "(Static Info) United States ETFs'", 'verbose_name_plural': "(Static Info) United States ETFs'"},
        ),
        migrations.AlterModelOptions(
            name='usfundstaticinfo',
            options={'verbose_name': "(Static Info) United States Funds'", 'verbose_name_plural': "(Static Info) United States Funds'"},
        ),
        migrations.AlterModelOptions(
            name='usindexstaticinfo',
            options={'verbose_name': '(Static Info) United States Indices', 'verbose_name_plural': '(Static Info) United States Indices'},
        ),
        migrations.AlterModelOptions(
            name='usstockstaticinfo',
            options={'verbose_name': '(Static Info) United States Stocks', 'verbose_name_plural': '(Static Info) United States Stocks'},
        ),
    ]
