# Generated by Django 2.2.7 on 2019-12-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0091_auto_20191228_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='commoditystaticinfo',
            name='unit',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
