# Generated by Django 2.2.7 on 2019-12-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0092_commoditystaticinfo_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='australiabondstaticinfo',
            name='Type',
            field=models.CharField(choices=[('cmdty', 'Commodity'), ('crncy', 'Currency'), ('crptcrncy', 'Cryptocurrency'), ('stck', 'Stock'), ('indx', 'Index'), ('etf', 'ETF'), ('bnd', 'Bond'), ('fnd', 'Fund')], default='bnd', max_length=9),
        ),
        migrations.AddField(
            model_name='australiaetfstaticinfo',
            name='Type',
            field=models.CharField(choices=[('cmdty', 'Commodity'), ('crncy', 'Currency'), ('crptcrncy', 'Cryptocurrency'), ('stck', 'Stock'), ('indx', 'Index'), ('etf', 'ETF'), ('bnd', 'Bond'), ('fnd', 'Fund')], default='etf', max_length=9),
        ),
        migrations.AddField(
            model_name='australiafundstaticinfo',
            name='Type',
            field=models.CharField(choices=[('cmdty', 'Commodity'), ('crncy', 'Currency'), ('crptcrncy', 'Cryptocurrency'), ('stck', 'Stock'), ('indx', 'Index'), ('etf', 'ETF'), ('bnd', 'Bond'), ('fnd', 'Fund')], default='fnd', max_length=9),
        ),
        migrations.AddField(
            model_name='australiaindexstaticinfo',
            name='Type',
            field=models.CharField(choices=[('cmdty', 'Commodity'), ('crncy', 'Currency'), ('crptcrncy', 'Cryptocurrency'), ('stck', 'Stock'), ('indx', 'Index'), ('etf', 'ETF'), ('bnd', 'Bond'), ('fnd', 'Fund')], default='indx', max_length=9),
        ),
        migrations.AddField(
            model_name='australiastockstaticinfo',
            name='Type',
            field=models.CharField(choices=[('cmdty', 'Commodity'), ('crncy', 'Currency'), ('crptcrncy', 'Cryptocurrency'), ('stck', 'Stock'), ('indx', 'Index'), ('etf', 'ETF'), ('bnd', 'Bond'), ('fnd', 'Fund')], default='stck', max_length=9),
        ),
        migrations.AddField(
            model_name='canadabondstaticinfo',
            name='Type',
            field=models.CharField(choices=[('cmdty', 'Commodity'), ('crncy', 'Currency'), ('crptcrncy', 'Cryptocurrency'), ('stck', 'Stock'), ('indx', 'Index'), ('etf', 'ETF'), ('bnd', 'Bond'), ('fnd', 'Fund')], default='bnd', max_length=9),
        ),
        migrations.AddField(
            model_name='canadaetfstaticinfo',
            name='Type',
            field=models.CharField(choices=[('cmdty', 'Commodity'), ('crncy', 'Currency'), ('crptcrncy', 'Cryptocurrency'), ('stck', 'Stock'), ('indx', 'Index'), ('etf', 'ETF'), ('bnd', 'Bond'), ('fnd', 'Fund')], default='etf', max_length=9),
        ),
        migrations.AddField(
            model_name='canadafundstaticinfo',
            name='Type',
            field=models.CharField(choices=[('cmdty', 'Commodity'), ('crncy', 'Currency'), ('crptcrncy', 'Cryptocurrency'), ('stck', 'Stock'), ('indx', 'Index'), ('etf', 'ETF'), ('bnd', 'Bond'), ('fnd', 'Fund')], default='fnd', max_length=9),
        ),
        migrations.AddField(
            model_name='canadaindexstaticinfo',
            name='Type',
            field=models.CharField(choices=[('cmdty', 'Commodity'), ('crncy', 'Currency'), ('crptcrncy', 'Cryptocurrency'), ('stck', 'Stock'), ('indx', 'Index'), ('etf', 'ETF'), ('bnd', 'Bond'), ('fnd', 'Fund')], default='indx', max_length=9),
        ),
        migrations.AddField(
            model_name='canadastockstaticinfo',
            name='Type',
            field=models.CharField(choices=[('cmdty', 'Commodity'), ('crncy', 'Currency'), ('crptcrncy', 'Cryptocurrency'), ('stck', 'Stock'), ('indx', 'Index'), ('etf', 'ETF'), ('bnd', 'Bond'), ('fnd', 'Fund')], default='stck', max_length=9),
        ),
        migrations.AddField(
            model_name='chinabondstaticinfo',
            name='Type',
            field=models.CharField(choices=[('cmdty', 'Commodity'), ('crncy', 'Currency'), ('crptcrncy', 'Cryptocurrency'), ('stck', 'Stock'), ('indx', 'Index'), ('etf', 'ETF'), ('bnd', 'Bond'), ('fnd', 'Fund')], default='bnd', max_length=9),
        ),
        migrations.AddField(
            model_name='chinaetfstaticinfo',
            name='Type',
            field=models.CharField(choices=[('cmdty', 'Commodity'), ('crncy', 'Currency'), ('crptcrncy', 'Cryptocurrency'), ('stck', 'Stock'), ('indx', 'Index'), ('etf', 'ETF'), ('bnd', 'Bond'), ('fnd', 'Fund')], default='etf', max_length=9),
        ),
        migrations.AddField(
            model_name='chinafundstaticinfo',
            name='Type',
            field=models.CharField(choices=[('cmdty', 'Commodity'), ('crncy', 'Currency'), ('crptcrncy', 'Cryptocurrency'), ('stck', 'Stock'), ('indx', 'Index'), ('etf', 'ETF'), ('bnd', 'Bond'), ('fnd', 'Fund')], default='fnd', max_length=9),
        ),
        migrations.AddField(
            model_name='chinaindexstaticinfo',
            name='Type',
            field=models.CharField(choices=[('cmdty', 'Commodity'), ('crncy', 'Currency'), ('crptcrncy', 'Cryptocurrency'), ('stck', 'Stock'), ('indx', 'Index'), ('etf', 'ETF'), ('bnd', 'Bond'), ('fnd', 'Fund')], default='indx', max_length=9),
        ),
        migrations.AddField(
            model_name='chinastockstaticinfo',
            name='Type',
            field=models.CharField(choices=[('cmdty', 'Commodity'), ('crncy', 'Currency'), ('crptcrncy', 'Cryptocurrency'), ('stck', 'Stock'), ('indx', 'Index'), ('etf', 'ETF'), ('bnd', 'Bond'), ('fnd', 'Fund')], default='stck', max_length=9),
        ),
        migrations.AddField(
            model_name='commoditystaticinfo',
            name='Type',
            field=models.CharField(choices=[('cmdty', 'Commodity'), ('crncy', 'Currency'), ('crptcrncy', 'Cryptocurrency'), ('stck', 'Stock'), ('indx', 'Index'), ('etf', 'ETF'), ('bnd', 'Bond'), ('fnd', 'Fund')], default='cmdty', max_length=9),
        ),
        migrations.AddField(
            model_name='cryptocurrencystaticinfo',
            name='Type',
            field=models.CharField(choices=[('cmdty', 'Commodity'), ('crncy', 'Currency'), ('crptcrncy', 'Cryptocurrency'), ('stck', 'Stock'), ('indx', 'Index'), ('etf', 'ETF'), ('bnd', 'Bond'), ('fnd', 'Fund')], default='crptcrncy', max_length=9),
        ),
        migrations.AddField(
            model_name='currencystaticinfo',
            name='Type',
            field=models.CharField(choices=[('cmdty', 'Commodity'), ('crncy', 'Currency'), ('crptcrncy', 'Cryptocurrency'), ('stck', 'Stock'), ('indx', 'Index'), ('etf', 'ETF'), ('bnd', 'Bond'), ('fnd', 'Fund')], default='crncy', max_length=9),
        ),
        migrations.AddField(
            model_name='germanybondstaticinfo',
            name='Type',
            field=models.CharField(choices=[('cmdty', 'Commodity'), ('crncy', 'Currency'), ('crptcrncy', 'Cryptocurrency'), ('stck', 'Stock'), ('indx', 'Index'), ('etf', 'ETF'), ('bnd', 'Bond'), ('fnd', 'Fund')], default='bnd', max_length=9),
        ),
        migrations.AddField(
            model_name='germanyetfstaticinfo',
            name='Type',
            field=models.CharField(choices=[('cmdty', 'Commodity'), ('crncy', 'Currency'), ('crptcrncy', 'Cryptocurrency'), ('stck', 'Stock'), ('indx', 'Index'), ('etf', 'ETF'), ('bnd', 'Bond'), ('fnd', 'Fund')], default='etf', max_length=9),
        ),
        migrations.AddField(
            model_name='germanyfundstaticinfo',
            name='Type',
            field=models.CharField(choices=[('cmdty', 'Commodity'), ('crncy', 'Currency'), ('crptcrncy', 'Cryptocurrency'), ('stck', 'Stock'), ('indx', 'Index'), ('etf', 'ETF'), ('bnd', 'Bond'), ('fnd', 'Fund')], default='fnd', max_length=9),
        ),
        migrations.AddField(
            model_name='germanyindexstaticinfo',
            name='Type',
            field=models.CharField(choices=[('cmdty', 'Commodity'), ('crncy', 'Currency'), ('crptcrncy', 'Cryptocurrency'), ('stck', 'Stock'), ('indx', 'Index'), ('etf', 'ETF'), ('bnd', 'Bond'), ('fnd', 'Fund')], default='indx', max_length=9),
        ),
        migrations.AddField(
            model_name='germanystockstaticinfo',
            name='Type',
            field=models.CharField(choices=[('cmdty', 'Commodity'), ('crncy', 'Currency'), ('crptcrncy', 'Cryptocurrency'), ('stck', 'Stock'), ('indx', 'Index'), ('etf', 'ETF'), ('bnd', 'Bond'), ('fnd', 'Fund')], default='stck', max_length=9),
        ),
        migrations.AddField(
            model_name='hkbondstaticinfo',
            name='Type',
            field=models.CharField(choices=[('cmdty', 'Commodity'), ('crncy', 'Currency'), ('crptcrncy', 'Cryptocurrency'), ('stck', 'Stock'), ('indx', 'Index'), ('etf', 'ETF'), ('bnd', 'Bond'), ('fnd', 'Fund')], default='bnd', max_length=9),
        ),
        migrations.AddField(
            model_name='hketfstaticinfo',
            name='Type',
            field=models.CharField(choices=[('cmdty', 'Commodity'), ('crncy', 'Currency'), ('crptcrncy', 'Cryptocurrency'), ('stck', 'Stock'), ('indx', 'Index'), ('etf', 'ETF'), ('bnd', 'Bond'), ('fnd', 'Fund')], default='etf', max_length=9),
        ),
        migrations.AddField(
            model_name='hkfundstaticinfo',
            name='Type',
            field=models.CharField(choices=[('cmdty', 'Commodity'), ('crncy', 'Currency'), ('crptcrncy', 'Cryptocurrency'), ('stck', 'Stock'), ('indx', 'Index'), ('etf', 'ETF'), ('bnd', 'Bond'), ('fnd', 'Fund')], default='fnd', max_length=9),
        ),
        migrations.AddField(
            model_name='hkindexstaticinfo',
            name='Type',
            field=models.CharField(choices=[('cmdty', 'Commodity'), ('crncy', 'Currency'), ('crptcrncy', 'Cryptocurrency'), ('stck', 'Stock'), ('indx', 'Index'), ('etf', 'ETF'), ('bnd', 'Bond'), ('fnd', 'Fund')], default='indx', max_length=9),
        ),
        migrations.AddField(
            model_name='hkstockstaticinfo',
            name='Type',
            field=models.CharField(choices=[('cmdty', 'Commodity'), ('crncy', 'Currency'), ('crptcrncy', 'Cryptocurrency'), ('stck', 'Stock'), ('indx', 'Index'), ('etf', 'ETF'), ('bnd', 'Bond'), ('fnd', 'Fund')], default='stck', max_length=9),
        ),
        migrations.AddField(
            model_name='japanbondstaticinfo',
            name='Type',
            field=models.CharField(choices=[('cmdty', 'Commodity'), ('crncy', 'Currency'), ('crptcrncy', 'Cryptocurrency'), ('stck', 'Stock'), ('indx', 'Index'), ('etf', 'ETF'), ('bnd', 'Bond'), ('fnd', 'Fund')], default='bnd', max_length=9),
        ),
        migrations.AddField(
            model_name='japanetfstaticinfo',
            name='Type',
            field=models.CharField(choices=[('cmdty', 'Commodity'), ('crncy', 'Currency'), ('crptcrncy', 'Cryptocurrency'), ('stck', 'Stock'), ('indx', 'Index'), ('etf', 'ETF'), ('bnd', 'Bond'), ('fnd', 'Fund')], default='etf', max_length=9),
        ),
        migrations.AddField(
            model_name='japanfundstaticinfo',
            name='Type',
            field=models.CharField(choices=[('cmdty', 'Commodity'), ('crncy', 'Currency'), ('crptcrncy', 'Cryptocurrency'), ('stck', 'Stock'), ('indx', 'Index'), ('etf', 'ETF'), ('bnd', 'Bond'), ('fnd', 'Fund')], default='fnd', max_length=9),
        ),
        migrations.AddField(
            model_name='japanindexstaticinfo',
            name='Type',
            field=models.CharField(choices=[('cmdty', 'Commodity'), ('crncy', 'Currency'), ('crptcrncy', 'Cryptocurrency'), ('stck', 'Stock'), ('indx', 'Index'), ('etf', 'ETF'), ('bnd', 'Bond'), ('fnd', 'Fund')], default='indx', max_length=9),
        ),
        migrations.AddField(
            model_name='japanstockstaticinfo',
            name='Type',
            field=models.CharField(choices=[('cmdty', 'Commodity'), ('crncy', 'Currency'), ('crptcrncy', 'Cryptocurrency'), ('stck', 'Stock'), ('indx', 'Index'), ('etf', 'ETF'), ('bnd', 'Bond'), ('fnd', 'Fund')], default='stck', max_length=9),
        ),
        migrations.AddField(
            model_name='ukbondstaticinfo',
            name='Type',
            field=models.CharField(choices=[('cmdty', 'Commodity'), ('crncy', 'Currency'), ('crptcrncy', 'Cryptocurrency'), ('stck', 'Stock'), ('indx', 'Index'), ('etf', 'ETF'), ('bnd', 'Bond'), ('fnd', 'Fund')], default='bnd', max_length=9),
        ),
        migrations.AddField(
            model_name='uketfstaticinfo',
            name='Type',
            field=models.CharField(choices=[('cmdty', 'Commodity'), ('crncy', 'Currency'), ('crptcrncy', 'Cryptocurrency'), ('stck', 'Stock'), ('indx', 'Index'), ('etf', 'ETF'), ('bnd', 'Bond'), ('fnd', 'Fund')], default='etf', max_length=9),
        ),
        migrations.AddField(
            model_name='ukfundstaticinfo',
            name='Type',
            field=models.CharField(choices=[('cmdty', 'Commodity'), ('crncy', 'Currency'), ('crptcrncy', 'Cryptocurrency'), ('stck', 'Stock'), ('indx', 'Index'), ('etf', 'ETF'), ('bnd', 'Bond'), ('fnd', 'Fund')], default='fnd', max_length=9),
        ),
        migrations.AddField(
            model_name='ukindexstaticinfo',
            name='Type',
            field=models.CharField(choices=[('cmdty', 'Commodity'), ('crncy', 'Currency'), ('crptcrncy', 'Cryptocurrency'), ('stck', 'Stock'), ('indx', 'Index'), ('etf', 'ETF'), ('bnd', 'Bond'), ('fnd', 'Fund')], default='indx', max_length=9),
        ),
        migrations.AddField(
            model_name='ukstockstaticinfo',
            name='Type',
            field=models.CharField(choices=[('cmdty', 'Commodity'), ('crncy', 'Currency'), ('crptcrncy', 'Cryptocurrency'), ('stck', 'Stock'), ('indx', 'Index'), ('etf', 'ETF'), ('bnd', 'Bond'), ('fnd', 'Fund')], default='stck', max_length=9),
        ),
        migrations.AddField(
            model_name='usbondstaticinfo',
            name='Type',
            field=models.CharField(choices=[('cmdty', 'Commodity'), ('crncy', 'Currency'), ('crptcrncy', 'Cryptocurrency'), ('stck', 'Stock'), ('indx', 'Index'), ('etf', 'ETF'), ('bnd', 'Bond'), ('fnd', 'Fund')], default='bnd', max_length=9),
        ),
        migrations.AddField(
            model_name='usetfstaticinfo',
            name='Type',
            field=models.CharField(choices=[('cmdty', 'Commodity'), ('crncy', 'Currency'), ('crptcrncy', 'Cryptocurrency'), ('stck', 'Stock'), ('indx', 'Index'), ('etf', 'ETF'), ('bnd', 'Bond'), ('fnd', 'Fund')], default='etf', max_length=9),
        ),
        migrations.AddField(
            model_name='usfundstaticinfo',
            name='Type',
            field=models.CharField(choices=[('cmdty', 'Commodity'), ('crncy', 'Currency'), ('crptcrncy', 'Cryptocurrency'), ('stck', 'Stock'), ('indx', 'Index'), ('etf', 'ETF'), ('bnd', 'Bond'), ('fnd', 'Fund')], default='fnd', max_length=9),
        ),
        migrations.AddField(
            model_name='usindexstaticinfo',
            name='Type',
            field=models.CharField(choices=[('cmdty', 'Commodity'), ('crncy', 'Currency'), ('crptcrncy', 'Cryptocurrency'), ('stck', 'Stock'), ('indx', 'Index'), ('etf', 'ETF'), ('bnd', 'Bond'), ('fnd', 'Fund')], default='indx', max_length=9),
        ),
        migrations.AddField(
            model_name='usstockstaticinfo',
            name='Type',
            field=models.CharField(choices=[('cmdty', 'Commodity'), ('crncy', 'Currency'), ('crptcrncy', 'Cryptocurrency'), ('stck', 'Stock'), ('indx', 'Index'), ('etf', 'ETF'), ('bnd', 'Bond'), ('fnd', 'Fund')], default='stck', max_length=9),
        ),
    ]
