# Generated by Django 2.2.7 on 2019-12-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0093_auto_20191228_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='australiafundstaticinfo',
            name='inception_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='canadafundstaticinfo',
            name='inception_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='chinafundstaticinfo',
            name='inception_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='commoditystaticinfo',
            name='unit',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='germanyfundstaticinfo',
            name='inception_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='hkfundstaticinfo',
            name='inception_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='japanfundstaticinfo',
            name='inception_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ukfundstaticinfo',
            name='inception_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='usfundstaticinfo',
            name='inception_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
