# Generated by Django 2.2.7 on 2019-12-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0094_auto_20191229_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllAssetsHistoricalMax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('cmdty', 'Commodity'), ('crncy', 'Currency'), ('crptcrncy', 'Cryptocurrency'), ('stck', 'Stock'), ('indx', 'Index'), ('etf', 'ETF'), ('bnd', 'Bond'), ('fnd', 'Fund')], max_length=9)),
                ('country', models.CharField(choices=[('G', 'Global'), ('US', 'United States of America'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], max_length=2)),
                ('short_name', models.CharField(max_length=18)),
                ('date', models.DateField(default=None, null=True)),
                ('price', models.CharField(default=None, max_length=12, null=True)),
                ('Open', models.CharField(default=None, max_length=12, null=True)),
                ('high', models.CharField(default=None, max_length=12, null=True)),
                ('low', models.CharField(default=None, max_length=12, null=True)),
                ('volume', models.CharField(default=None, max_length=12, null=True)),
            ],
            options={
                'verbose_name': '(Max Years) All Asset Types',
                'verbose_name_plural': '(Max Years) All Asset Types',
            },
        ),
    ]
