# Generated by Django 2.2.7 on 2019-12-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0095_allassetshistoricalmax'),
    ]

    operations = [
        migrations.AddField(
            model_name='allassetshistoricalmax',
            name='change_perc',
            field=models.CharField(default=None, max_length=12, null=True),
        ),
    ]
