# Generated by Django 2.2.7 on 2020-01-11 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0096_allassetshistoricalmax_change_perc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cryptocurrencystaticinfo',
            options={'verbose_name': '(Static Info) Cryptocurrencies', 'verbose_name_plural': '(Static Info) Cryptocurrencies'},
        ),
    ]
