# Generated by Django 2.2.7 on 2020-01-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0099_auto_20200122_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commoditystaticinfo',
            name='unit',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
