# Generated by Django 3.0.2 on 2020-01-25 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0100_auto_20200125_0329'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommodityAfterLive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('cmdty', 'Commodity'), ('crncy', 'Currency'), ('crptcrncy', 'Cryptocurrency'), ('stck', 'Stock'), ('indx', 'Index'), ('etf', 'ETF'), ('bnd', 'Bond'), ('fnd', 'Fund')], default='cmdty', max_length=9)),
                ('short_name', models.CharField(max_length=16)),
                ('link', models.URLField()),
                ('date', models.DateField(default=datetime.date.today, null=True)),
                ('one_year_rng', models.CharField(max_length=30)),
                ('one_year_chg', models.CharField(max_length=7)),
                ('month', models.DateField(default=None, null=True)),
                ('settlement_day', models.DateField(default=None, null=True)),
                ('last_roll_day', models.DateField(default=None, null=True)),
            ],
            options={
                'verbose_name': '(After Live Commodities)',
                'verbose_name_plural': '(After Live Commodities)',
            },
        ),
        migrations.CreateModel(
            name='CommodityBeforeLive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('cmdty', 'Commodity'), ('crncy', 'Currency'), ('crptcrncy', 'Cryptocurrency'), ('stck', 'Stock'), ('indx', 'Index'), ('etf', 'ETF'), ('bnd', 'Bond'), ('fnd', 'Fund')], default='cmdty', max_length=9)),
                ('short_name', models.CharField(max_length=16)),
                ('link', models.URLField()),
                ('prev_close', models.CharField(max_length=15, null=True)),
                ('Open', models.CharField(max_length=15, null=True)),
            ],
            options={
                'verbose_name': '(Before Live Commodities)',
                'verbose_name_plural': '(Before Live Commodities)',
            },
        ),
        migrations.CreateModel(
            name='CommodityHistorical1D',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('cmdty', 'Commodity'), ('crncy', 'Currency'), ('crptcrncy', 'Cryptocurrency'), ('stck', 'Stock'), ('indx', 'Index'), ('etf', 'ETF'), ('bnd', 'Bond'), ('fnd', 'Fund')], default='cmdty', max_length=9)),
                ('short_name', models.CharField(max_length=16)),
                ('link', models.URLField()),
                ('date', models.DateTimeField(default=None, null=True)),
                ('price', models.CharField(default=None, max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommodityLive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('cmdty', 'Commodity'), ('crncy', 'Currency'), ('crptcrncy', 'Cryptocurrency'), ('stck', 'Stock'), ('indx', 'Index'), ('etf', 'ETF'), ('bnd', 'Bond'), ('fnd', 'Fund')], default='cmdty', max_length=9)),
                ('short_name', models.CharField(max_length=16)),
                ('link', models.URLField()),
                ('high', models.CharField(max_length=15, null=True)),
                ('low', models.CharField(max_length=15, null=True)),
                ('change', models.CharField(max_length=15, null=True)),
                ('change_perc', models.CharField(max_length=12, null=True)),
            ],
            options={
                'verbose_name': '(Live Commodities) All Asset Types',
                'verbose_name_plural': '(Live Commodities) All Asset Types',
            },
        ),
    ]
