# Generated by Django 3.0.2 on 2020-01-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0101_commodityafterlive_commoditybeforelive_commodityhistorical1d_commoditylive'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommodityHistorical5D',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('cmdty', 'Commodity'), ('crncy', 'Currency'), ('crptcrncy', 'Cryptocurrency'), ('stck', 'Stock'), ('indx', 'Index'), ('etf', 'ETF'), ('bnd', 'Bond'), ('fnd', 'Fund')], default='cmdty', max_length=9)),
                ('short_name', models.CharField(max_length=16)),
                ('link', models.URLField()),
                ('date', models.DateTimeField(default=None, null=True)),
                ('price', models.CharField(default=None, max_length=12, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='commodityafterlive',
            old_name='month',
            new_name='months',
        ),
        migrations.AddField(
            model_name='commoditybeforelive',
            name='date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='commoditylive',
            name='last_price',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='commoditylive',
            name='last_price_time',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='commoditylive',
            name='month',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='commodityafterlive',
            name='date',
            field=models.DateField(default=None, null=True),
        ),
    ]
