# Generated by Django 3.0.2 on 2020-01-25 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0102_auto_20200125_0653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commodityhistorical1d',
            options={'verbose_name': '(1 Day) Commodities', 'verbose_name_plural': '(1 Day) Commodities'},
        ),
        migrations.AlterModelOptions(
            name='commodityhistorical5d',
            options={'verbose_name': '(5 Days) Commodities', 'verbose_name_plural': '(5 Days) Commodities'},
        ),
    ]
