# Generated by Django 3.0.2 on 2020-01-25 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0103_auto_20200125_0934'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommodityAfterLive',
        ),
    ]
