# Generated by Django 3.0.2 on 2020-01-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0104_delete_commodityafterlive'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommodityAfterLive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('cmdty', 'Commodity'), ('crncy', 'Currency'), ('crptcrncy', 'Cryptocurrency'), ('stck', 'Stock'), ('indx', 'Index'), ('etf', 'ETF'), ('bnd', 'Bond'), ('fnd', 'Fund')], default='cmdty', max_length=9)),
                ('short_name', models.CharField(max_length=16)),
                ('link', models.URLField()),
                ('date', models.DateField(default=None, null=True)),
                ('one_year_rng', models.CharField(max_length=30)),
                ('one_year_chg', models.CharField(max_length=7)),
                ('months', models.CharField(max_length=15)),
                ('settlement_day', models.DateField(default=None, null=True)),
                ('last_roll_day', models.DateField(default=None, null=True)),
            ],
            options={
                'verbose_name': '(After Live Commodities)',
                'verbose_name_plural': '(After Live Commodities)',
            },
        ),
    ]
