# Generated by Django 2.2.5 on 2020-02-08 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0108_auto_20200206_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrencystaticinfo',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
