# Generated by Django 2.2.5 on 2020-02-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0110_auto_20200207_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllAssetsHistorical1Y',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('cmdty', 'Commodity'), ('crncy', 'Currency'), ('crptcrncy', 'Cryptocurrency'), ('stck', 'Stock'), ('indx', 'Index'), ('etf', 'ETF'), ('bnd', 'Bond'), ('fnd', 'Fund')], max_length=9)),
                ('short_name', models.CharField(max_length=18)),
                ('link', models.URLField(null=True)),
                ('date', models.DateField(default=None, null=True)),
                ('price', models.CharField(default=None, max_length=12, null=True)),
                ('volume', models.CharField(default=None, max_length=12, null=True)),
            ],
            options={
                'verbose_name': '(1 Year) All Assets',
                'verbose_name_plural': '(1 Year) All Assets',
            },
        ),
        migrations.CreateModel(
            name='AllAssetsHistorical6M1M',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('cmdty', 'Commodity'), ('crncy', 'Currency'), ('crptcrncy', 'Cryptocurrency'), ('stck', 'Stock'), ('indx', 'Index'), ('etf', 'ETF'), ('bnd', 'Bond'), ('fnd', 'Fund')], max_length=9)),
                ('short_name', models.CharField(max_length=18)),
                ('link', models.URLField(null=True)),
                ('date', models.DateField(default=None, null=True)),
                ('price', models.CharField(default=None, max_length=12, null=True)),
                ('volume', models.CharField(default=None, max_length=12, null=True)),
            ],
            options={
                'verbose_name': '(6M-1M) All Assets',
                'verbose_name_plural': '(6M-1M) All Assets',
            },
        ),
        migrations.AlterModelOptions(
            name='allassetshistorical5y',
            options={'verbose_name': '(5 Years) All Assets', 'verbose_name_plural': '(5 Years) All Assets'},
        ),
        migrations.AlterModelOptions(
            name='allassetshistoricalmax',
            options={'verbose_name': '(Max Years) All Assets', 'verbose_name_plural': '(Max Years) All Assets'},
        ),
        migrations.RemoveField(
            model_name='allassetshistorical5y',
            name='Open',
        ),
        migrations.RemoveField(
            model_name='allassetshistorical5y',
            name='change_perc',
        ),
        migrations.RemoveField(
            model_name='allassetshistorical5y',
            name='country',
        ),
        migrations.RemoveField(
            model_name='allassetshistorical5y',
            name='high',
        ),
        migrations.RemoveField(
            model_name='allassetshistorical5y',
            name='low',
        ),
        migrations.RemoveField(
            model_name='allassetshistoricalmax',
            name='Open',
        ),
        migrations.RemoveField(
            model_name='allassetshistoricalmax',
            name='change_perc',
        ),
        migrations.RemoveField(
            model_name='allassetshistoricalmax',
            name='country',
        ),
        migrations.RemoveField(
            model_name='allassetshistoricalmax',
            name='high',
        ),
        migrations.RemoveField(
            model_name='allassetshistoricalmax',
            name='low',
        ),
        migrations.AddField(
            model_name='allassetshistorical1d',
            name='volume',
            field=models.CharField(default=None, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='allassetshistorical5d',
            name='volume',
            field=models.CharField(default=None, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='allassetshistorical5y',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='allassetshistoricalmax',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='allassetslive',
            name='volume',
            field=models.CharField(default=None, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='allassetsafterlive',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='allassetsbeforelive',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='allassetshistorical1d',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='allassetshistorical5d',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='allassetslive',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='australiaetfstaticinfo',
            name='issuer',
            field=models.CharField(max_length=38),
        ),
        migrations.AlterField(
            model_name='australiafundstaticinfo',
            name='issuer',
            field=models.CharField(max_length=39),
        ),
        migrations.AlterField(
            model_name='canadaetfstaticinfo',
            name='issuer',
            field=models.CharField(max_length=37),
        ),
        migrations.AlterField(
            model_name='canadafundstaticinfo',
            name='issuer',
            field=models.CharField(max_length=33),
        ),
        migrations.AlterField(
            model_name='chinaetfstaticinfo',
            name='issuer',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='chinafundstaticinfo',
            name='issuer',
            field=models.CharField(max_length=39),
        ),
        migrations.AlterField(
            model_name='germanyetfstaticinfo',
            name='issuer',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='germanyfundstaticinfo',
            name='issuer',
            field=models.CharField(max_length=41),
        ),
        migrations.AlterField(
            model_name='hketfstaticinfo',
            name='issuer',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='hkfundstaticinfo',
            name='issuer',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='japanetfstaticinfo',
            name='issuer',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='japanfundstaticinfo',
            name='issuer',
            field=models.CharField(max_length=48),
        ),
        migrations.AlterField(
            model_name='uketfstaticinfo',
            name='issuer',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='ukfundstaticinfo',
            name='issuer',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usetfstaticinfo',
            name='issuer',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='usfundstaticinfo',
            name='issuer',
            field=models.CharField(max_length=30),
        ),
    ]
