# Generated by Django 3.0.3 on 2020-02-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0112_auto_20200212_1032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allassetshistorical1d',
            options={'verbose_name': '(Historical 1 Day) All Assets', 'verbose_name_plural': '(Historical 1 Day) All Assets'},
        ),
        migrations.AlterModelOptions(
            name='allassetshistorical1y',
            options={'verbose_name': '(Historical 1 Year) All Assets', 'verbose_name_plural': '(Historical 1 Year) All Assets'},
        ),
        migrations.AlterModelOptions(
            name='allassetshistorical5d',
            options={'verbose_name': '(Historical 5 Days) All Assets', 'verbose_name_plural': '(Historical 5 Days) All Assets'},
        ),
        migrations.AlterModelOptions(
            name='allassetshistorical5y',
            options={'verbose_name': '(Historical 5 Years) All Assets', 'verbose_name_plural': '(Historical 5 Years) All Assets'},
        ),
        migrations.AlterModelOptions(
            name='allassetshistorical6m1m',
            options={'verbose_name': '(Historical 6M-1M) All Assets', 'verbose_name_plural': '(Historical 6M-1M) All Assets'},
        ),
        migrations.AlterModelOptions(
            name='allassetshistoricalmax',
            options={'verbose_name': '(Historical Max Years) All Assets', 'verbose_name_plural': '(Historical Max Years) All Assets'},
        ),
        migrations.AddField(
            model_name='allassetshistorical1d',
            name='Open',
            field=models.CharField(default=None, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='allassetshistorical1d',
            name='high',
            field=models.CharField(default=None, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='allassetshistorical1d',
            name='low',
            field=models.CharField(default=None, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='allassetshistorical1y',
            name='Open',
            field=models.CharField(default=None, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='allassetshistorical1y',
            name='high',
            field=models.CharField(default=None, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='allassetshistorical1y',
            name='low',
            field=models.CharField(default=None, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='allassetshistorical5d',
            name='Open',
            field=models.CharField(default=None, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='allassetshistorical5d',
            name='high',
            field=models.CharField(default=None, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='allassetshistorical5d',
            name='low',
            field=models.CharField(default=None, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='allassetshistorical5y',
            name='Open',
            field=models.CharField(default=None, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='allassetshistorical5y',
            name='high',
            field=models.CharField(default=None, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='allassetshistorical5y',
            name='low',
            field=models.CharField(default=None, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='allassetshistorical6m1m',
            name='Open',
            field=models.CharField(default=None, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='allassetshistorical6m1m',
            name='high',
            field=models.CharField(default=None, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='allassetshistorical6m1m',
            name='low',
            field=models.CharField(default=None, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='allassetshistoricalmax',
            name='Open',
            field=models.CharField(default=None, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='allassetshistoricalmax',
            name='high',
            field=models.CharField(default=None, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='allassetshistoricalmax',
            name='low',
            field=models.CharField(default=None, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='australiaetfstaticinfo',
            name='issuer',
            field=models.CharField(choices=[], max_length=38),
        ),
        migrations.AlterField(
            model_name='australiafundstaticinfo',
            name='issuer',
            field=models.CharField(choices=[], max_length=39),
        ),
        migrations.AlterField(
            model_name='canadaetfstaticinfo',
            name='issuer',
            field=models.CharField(choices=[], max_length=37),
        ),
        migrations.AlterField(
            model_name='canadafundstaticinfo',
            name='issuer',
            field=models.CharField(choices=[], max_length=33),
        ),
        migrations.AlterField(
            model_name='chinaetfstaticinfo',
            name='issuer',
            field=models.CharField(choices=[], max_length=40),
        ),
        migrations.AlterField(
            model_name='chinafundstaticinfo',
            name='issuer',
            field=models.CharField(choices=[], max_length=39),
        ),
        migrations.AlterField(
            model_name='germanyetfstaticinfo',
            name='issuer',
            field=models.CharField(choices=[], max_length=40),
        ),
        migrations.AlterField(
            model_name='germanyfundstaticinfo',
            name='issuer',
            field=models.CharField(choices=[], max_length=41),
        ),
        migrations.AlterField(
            model_name='hketfstaticinfo',
            name='issuer',
            field=models.CharField(choices=[], max_length=45),
        ),
        migrations.AlterField(
            model_name='hkfundstaticinfo',
            name='issuer',
            field=models.CharField(choices=[], max_length=50),
        ),
        migrations.AlterField(
            model_name='japanetfstaticinfo',
            name='issuer',
            field=models.CharField(choices=[], max_length=40),
        ),
        migrations.AlterField(
            model_name='japanfundstaticinfo',
            name='issuer',
            field=models.CharField(choices=[], max_length=48),
        ),
        migrations.AlterField(
            model_name='uketfstaticinfo',
            name='issuer',
            field=models.CharField(choices=[], max_length=40),
        ),
        migrations.AlterField(
            model_name='ukfundstaticinfo',
            name='issuer',
            field=models.CharField(choices=[], max_length=50),
        ),
        migrations.AlterField(
            model_name='usetfstaticinfo',
            name='issuer',
            field=models.CharField(choices=[], max_length=32),
        ),
        migrations.AlterField(
            model_name='usfundstaticinfo',
            name='issuer',
            field=models.CharField(choices=[], max_length=30),
        ),
    ]
