# Generated by Django 3.0.3 on 2020-02-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0113_auto_20200223_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allassetsafterlive',
            name='one_year_rng',
        ),
        migrations.RemoveField(
            model_name='commoditystaticinfo',
            name='months',
        ),
        migrations.AddField(
            model_name='allassetsafterlive',
            name='asset_class',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='allassetsafterlive',
            name='avg_vol_3m',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='allassetsafterlive',
            name='beta',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='allassetsafterlive',
            name='circ_supply',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='allassetsafterlive',
            name='coupon',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='allassetsafterlive',
            name='days_rng',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='allassetsafterlive',
            name='div_and_yield',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='allassetsafterlive',
            name='div_ttm',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='allassetsafterlive',
            name='div_yield',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='allassetsafterlive',
            name='eps',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='allassetsafterlive',
            name='expenses',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='allassetsafterlive',
            name='market_cap',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='allassetsafterlive',
            name='maturity_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='allassetsafterlive',
            name='max_supply',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='allassetsafterlive',
            name='next_earn_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='allassetsafterlive',
            name='pe_ratio',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='allassetsafterlive',
            name='price',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='allassetsafterlive',
            name='price_opn',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='allassetsafterlive',
            name='price_rng',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='allassetsafterlive',
            name='rating',
            field=models.CharField(default=None, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='allassetsafterlive',
            name='revenue',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='allassetsafterlive',
            name='risk_rating',
            field=models.CharField(default=None, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='allassetsafterlive',
            name='rng_52_wk',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='allassetsafterlive',
            name='roa',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='allassetsafterlive',
            name='roe',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='allassetsafterlive',
            name='roi_ttm',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='allassetsafterlive',
            name='shrs_outstndng',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='allassetsafterlive',
            name='total_assets',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='allassetsafterlive',
            name='ttm_yield',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='allassetsafterlive',
            name='turnover',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='allassetsafterlive',
            name='volume',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='allassetslive',
            name='Open',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='allassetslive',
            name='Yield',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='allassetslive',
            name='change_7d',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='allassetslive',
            name='market_cap',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='allassetslive',
            name='total_assets',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='allassetslive',
            name='total_vol',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='allassetsafterlive',
            name='months',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='allassetsafterlive',
            name='one_year_chg',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
    ]
