# Generated by Django 3.0.3 on 2020-02-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0114_auto_20200228_1127'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllAssetsBeforeLive',
        ),
        migrations.AddField(
            model_name='allassetslive',
            name='prev_close',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
