# Generated by Django 3.0.2 on 2020-02-29 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0118_auto_20200229_0422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allassetslive',
            name='last_price_time',
        ),
    ]
