# Generated by Django 3.0.3 on 2020-03-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0120_auto_20200307_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrencystaticinfo',
            name='country',
            field=models.CharField(choices=[('G', 'Global'), ('US', 'United States of America'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], default='G', max_length=2),
        ),
        migrations.AddField(
            model_name='currencystaticinfo',
            name='country',
            field=models.CharField(choices=[('G', 'Global'), ('US', 'United States of America'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], default='G', max_length=2),
        ),
    ]
