# Generated by Django 3.0.5 on 2020-04-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0122_auto_20200316_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='australiabondstaticinfo',
            name='country',
            field=models.CharField(choices=[('G', 'Global'), ('US', 'United States'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], default='AU', max_length=2),
        ),
        migrations.AlterField(
            model_name='australiaetfstaticinfo',
            name='country',
            field=models.CharField(choices=[('G', 'Global'), ('US', 'United States'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], default='AU', max_length=2),
        ),
        migrations.AlterField(
            model_name='australiaetfstaticinfo',
            name='issuer',
            field=models.CharField(choices=[], max_length=45),
        ),
        migrations.AlterField(
            model_name='australiafundstaticinfo',
            name='country',
            field=models.CharField(choices=[('G', 'Global'), ('US', 'United States'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], default='AU', max_length=2),
        ),
        migrations.AlterField(
            model_name='australiafundstaticinfo',
            name='issuer',
            field=models.CharField(choices=[], max_length=39),
        ),
        migrations.AlterField(
            model_name='australiaindexstaticinfo',
            name='country',
            field=models.CharField(choices=[('G', 'Global'), ('US', 'United States'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], default='AU', max_length=2),
        ),
        migrations.AlterField(
            model_name='australiastockstaticinfo',
            name='country',
            field=models.CharField(choices=[('G', 'Global'), ('US', 'United States'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], default='AU', max_length=2),
        ),
        migrations.AlterField(
            model_name='canadabondstaticinfo',
            name='country',
            field=models.CharField(choices=[('G', 'Global'), ('US', 'United States'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], default='CA', max_length=2),
        ),
        migrations.AlterField(
            model_name='canadaetfstaticinfo',
            name='country',
            field=models.CharField(choices=[('G', 'Global'), ('US', 'United States'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], default='CA', max_length=2),
        ),
        migrations.AlterField(
            model_name='canadaetfstaticinfo',
            name='issuer',
            field=models.CharField(choices=[], max_length=45),
        ),
        migrations.AlterField(
            model_name='canadafundstaticinfo',
            name='country',
            field=models.CharField(choices=[('G', 'Global'), ('US', 'United States'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], default='CA', max_length=2),
        ),
        migrations.AlterField(
            model_name='canadafundstaticinfo',
            name='issuer',
            field=models.CharField(choices=[], max_length=33),
        ),
        migrations.AlterField(
            model_name='canadaindexstaticinfo',
            name='country',
            field=models.CharField(choices=[('G', 'Global'), ('US', 'United States'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], default='CA', max_length=2),
        ),
        migrations.AlterField(
            model_name='canadastockstaticinfo',
            name='country',
            field=models.CharField(choices=[('G', 'Global'), ('US', 'United States'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], default='CA', max_length=2),
        ),
        migrations.AlterField(
            model_name='chinabondstaticinfo',
            name='country',
            field=models.CharField(choices=[('G', 'Global'), ('US', 'United States'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], default='CH', max_length=2),
        ),
        migrations.AlterField(
            model_name='chinaetfstaticinfo',
            name='country',
            field=models.CharField(choices=[('G', 'Global'), ('US', 'United States'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], default='CH', max_length=2),
        ),
        migrations.AlterField(
            model_name='chinaetfstaticinfo',
            name='issuer',
            field=models.CharField(choices=[], max_length=45),
        ),
        migrations.AlterField(
            model_name='chinafundstaticinfo',
            name='country',
            field=models.CharField(choices=[('G', 'Global'), ('US', 'United States'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], default='CH', max_length=2),
        ),
        migrations.AlterField(
            model_name='chinafundstaticinfo',
            name='issuer',
            field=models.CharField(choices=[], max_length=39),
        ),
        migrations.AlterField(
            model_name='chinaindexstaticinfo',
            name='country',
            field=models.CharField(choices=[('G', 'Global'), ('US', 'United States'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], default='CH', max_length=2),
        ),
        migrations.AlterField(
            model_name='chinastockstaticinfo',
            name='country',
            field=models.CharField(choices=[('G', 'Global'), ('US', 'United States'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], default='CH', max_length=2),
        ),
        migrations.AlterField(
            model_name='commoditystaticinfo',
            name='country',
            field=models.CharField(choices=[('G', 'Global'), ('US', 'United States'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], max_length=2),
        ),
        migrations.AlterField(
            model_name='cryptocurrencystaticinfo',
            name='country',
            field=models.CharField(choices=[('G', 'Global'), ('US', 'United States'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], default='G', max_length=2),
        ),
        migrations.AlterField(
            model_name='currencystaticinfo',
            name='country',
            field=models.CharField(choices=[('G', 'Global'), ('US', 'United States'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], default='G', max_length=2),
        ),
        migrations.AlterField(
            model_name='etfissuers',
            name='country',
            field=models.CharField(choices=[('G', 'Global'), ('US', 'United States'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], max_length=2),
        ),
        migrations.AlterField(
            model_name='fundissuers',
            name='country',
            field=models.CharField(choices=[('G', 'Global'), ('US', 'United States'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], max_length=2),
        ),
        migrations.AlterField(
            model_name='germanybondstaticinfo',
            name='country',
            field=models.CharField(choices=[('G', 'Global'), ('US', 'United States'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], default='GE', max_length=2),
        ),
        migrations.AlterField(
            model_name='germanyetfstaticinfo',
            name='country',
            field=models.CharField(choices=[('G', 'Global'), ('US', 'United States'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], default='GE', max_length=2),
        ),
        migrations.AlterField(
            model_name='germanyetfstaticinfo',
            name='issuer',
            field=models.CharField(choices=[], max_length=45),
        ),
        migrations.AlterField(
            model_name='germanyfundstaticinfo',
            name='country',
            field=models.CharField(choices=[('G', 'Global'), ('US', 'United States'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], default='GE', max_length=2),
        ),
        migrations.AlterField(
            model_name='germanyfundstaticinfo',
            name='issuer',
            field=models.CharField(choices=[], max_length=41),
        ),
        migrations.AlterField(
            model_name='germanyindexstaticinfo',
            name='country',
            field=models.CharField(choices=[('G', 'Global'), ('US', 'United States'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], default='GE', max_length=2),
        ),
        migrations.AlterField(
            model_name='germanystockstaticinfo',
            name='country',
            field=models.CharField(choices=[('G', 'Global'), ('US', 'United States'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], default='GE', max_length=2),
        ),
        migrations.AlterField(
            model_name='hkbondstaticinfo',
            name='country',
            field=models.CharField(choices=[('G', 'Global'), ('US', 'United States'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], default='HK', max_length=2),
        ),
        migrations.AlterField(
            model_name='hketfstaticinfo',
            name='country',
            field=models.CharField(choices=[('G', 'Global'), ('US', 'United States'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], default='HK', max_length=2),
        ),
        migrations.AlterField(
            model_name='hketfstaticinfo',
            name='issuer',
            field=models.CharField(choices=[], max_length=45),
        ),
        migrations.AlterField(
            model_name='hkfundstaticinfo',
            name='country',
            field=models.CharField(choices=[('G', 'Global'), ('US', 'United States'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], default='HK', max_length=2),
        ),
        migrations.AlterField(
            model_name='hkfundstaticinfo',
            name='issuer',
            field=models.CharField(choices=[], max_length=50),
        ),
        migrations.AlterField(
            model_name='hkindexstaticinfo',
            name='country',
            field=models.CharField(choices=[('G', 'Global'), ('US', 'United States'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], default='HK', max_length=2),
        ),
        migrations.AlterField(
            model_name='hkstockstaticinfo',
            name='country',
            field=models.CharField(choices=[('G', 'Global'), ('US', 'United States'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], default='HK', max_length=2),
        ),
        migrations.AlterField(
            model_name='japanbondstaticinfo',
            name='country',
            field=models.CharField(choices=[('G', 'Global'), ('US', 'United States'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], default='JP', max_length=2),
        ),
        migrations.AlterField(
            model_name='japanetfstaticinfo',
            name='country',
            field=models.CharField(choices=[('G', 'Global'), ('US', 'United States'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], default='JP', max_length=2),
        ),
        migrations.AlterField(
            model_name='japanetfstaticinfo',
            name='issuer',
            field=models.CharField(choices=[], max_length=40),
        ),
        migrations.AlterField(
            model_name='japanfundstaticinfo',
            name='country',
            field=models.CharField(choices=[('G', 'Global'), ('US', 'United States'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], default='JP', max_length=2),
        ),
        migrations.AlterField(
            model_name='japanfundstaticinfo',
            name='issuer',
            field=models.CharField(choices=[], max_length=48),
        ),
        migrations.AlterField(
            model_name='japanindexstaticinfo',
            name='country',
            field=models.CharField(choices=[('G', 'Global'), ('US', 'United States'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], default='JP', max_length=2),
        ),
        migrations.AlterField(
            model_name='japanstockstaticinfo',
            name='country',
            field=models.CharField(choices=[('G', 'Global'), ('US', 'United States'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], default='JP', max_length=2),
        ),
        migrations.AlterField(
            model_name='ukbondstaticinfo',
            name='country',
            field=models.CharField(choices=[('G', 'Global'), ('US', 'United States'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], default='UK', max_length=2),
        ),
        migrations.AlterField(
            model_name='uketfstaticinfo',
            name='country',
            field=models.CharField(choices=[('G', 'Global'), ('US', 'United States'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], default='UK', max_length=2),
        ),
        migrations.AlterField(
            model_name='uketfstaticinfo',
            name='issuer',
            field=models.CharField(choices=[], max_length=45),
        ),
        migrations.AlterField(
            model_name='ukfundstaticinfo',
            name='country',
            field=models.CharField(choices=[('G', 'Global'), ('US', 'United States'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], default='UK', max_length=2),
        ),
        migrations.AlterField(
            model_name='ukfundstaticinfo',
            name='issuer',
            field=models.CharField(choices=[], max_length=50),
        ),
        migrations.AlterField(
            model_name='ukindexstaticinfo',
            name='country',
            field=models.CharField(choices=[('G', 'Global'), ('US', 'United States'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], default='UK', max_length=2),
        ),
        migrations.AlterField(
            model_name='ukstockstaticinfo',
            name='country',
            field=models.CharField(choices=[('G', 'Global'), ('US', 'United States'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], default='UK', max_length=2),
        ),
        migrations.AlterField(
            model_name='usbondstaticinfo',
            name='country',
            field=models.CharField(choices=[('G', 'Global'), ('US', 'United States'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], default='US', max_length=2),
        ),
        migrations.AlterField(
            model_name='usetfstaticinfo',
            name='country',
            field=models.CharField(choices=[('G', 'Global'), ('US', 'United States'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], default='US', max_length=2),
        ),
        migrations.AlterField(
            model_name='usetfstaticinfo',
            name='issuer',
            field=models.CharField(choices=[], max_length=32),
        ),
        migrations.AlterField(
            model_name='usfundstaticinfo',
            name='country',
            field=models.CharField(choices=[('G', 'Global'), ('US', 'United States'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], default='US', max_length=2),
        ),
        migrations.AlterField(
            model_name='usfundstaticinfo',
            name='issuer',
            field=models.CharField(choices=[], max_length=30),
        ),
        migrations.AlterField(
            model_name='usindexstaticinfo',
            name='country',
            field=models.CharField(choices=[('G', 'Global'), ('US', 'United States'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], default='US', max_length=2),
        ),
        migrations.AlterField(
            model_name='usstockstaticinfo',
            name='country',
            field=models.CharField(choices=[('G', 'Global'), ('US', 'United States'), ('UK', 'United Kingdom'), ('JP', 'Japan'), ('HK', 'Hong Kong'), ('CH', 'China'), ('CA', 'Canada'), ('GE', 'Germany'), ('AU', 'Australia')], default='US', max_length=2),
        ),
    ]
