# Generated by Django 3.0.5 on 2020-04-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0123_auto_20200418_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='australiaetfstaticinfo',
            name='issuer',
            field=models.CharField(choices=[], max_length=100),
        ),
        migrations.AlterField(
            model_name='australiaetfstaticinfo',
            name='long_name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='canadaetfstaticinfo',
            name='issuer',
            field=models.CharField(choices=[], max_length=100),
        ),
        migrations.AlterField(
            model_name='canadaetfstaticinfo',
            name='long_name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='chinaetfstaticinfo',
            name='issuer',
            field=models.CharField(choices=[], max_length=100),
        ),
        migrations.AlterField(
            model_name='chinaetfstaticinfo',
            name='long_name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='germanyetfstaticinfo',
            name='issuer',
            field=models.CharField(choices=[], max_length=100),
        ),
        migrations.AlterField(
            model_name='germanyetfstaticinfo',
            name='long_name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='hketfstaticinfo',
            name='issuer',
            field=models.CharField(choices=[], max_length=100),
        ),
        migrations.AlterField(
            model_name='hketfstaticinfo',
            name='long_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='japanetfstaticinfo',
            name='issuer',
            field=models.CharField(choices=[], max_length=100),
        ),
        migrations.AlterField(
            model_name='japanetfstaticinfo',
            name='long_name',
            field=models.CharField(max_length=121),
        ),
        migrations.AlterField(
            model_name='uketfstaticinfo',
            name='issuer',
            field=models.CharField(choices=[], max_length=100),
        ),
        migrations.AlterField(
            model_name='uketfstaticinfo',
            name='long_name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='usetfstaticinfo',
            name='issuer',
            field=models.CharField(choices=[], max_length=100),
        ),
        migrations.AlterField(
            model_name='usetfstaticinfo',
            name='long_name',
            field=models.CharField(max_length=120),
        ),
    ]
