# Generated by Django 3.0.3 on 2020-04-26 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0123_auto_20200414_2108'),
        ('scraper_app', '0125_auto_20200419_2312'),
    ]

    operations = [
    ]
